### ISSUE TITLE
Could not load file or assembly

### ISSUE THREAD

**Issue by Blacke17** [roxaskeyheart/Chromatics#10]
Trying to enable Chromatics for my Razer Blackwidow Chroma (Everything is latest update) and i get an error that says...

Could not load file or assembly 'Corale.Colore, Version=3.0.2.0,
Culture=neutral, PublicKeyToken=null' or one of its dependencies. The
system cannot find the file specified.

**Comment by Blacke17** [comment]
![111](https://cloud.githubusercontent.com/assets/18624240/14758769/e0530c1a-08d8-11e6-847e-49a272ca0cb8.png)

**Comment by logicallysynced** [comment]
Did you install via ACT or manually by downloading the zip?

**Comment by Blacke17** [comment]
I installed via ACT

**Comment by logicallysynced** [comment]
This is a bug I have now identified in the ACT loading code. I will work to resolve this in the near future.

In the mean time, please download the attached zip, **right-click > properties > unblock** it and then extract and copy the **Corale.Colore.dll** file to the following directory:

**C > Users > YOU >AppData > Roaming > Advanced Combat Tracker > Plugins > lib**

Now open ACT and navigate to the Plugins tab. Remove any previous Chromatics related files from the list and select **Browse**. Then navigate to:

**C > Users > YOU >AppData > Roaming > Advanced Combat Tracker > Plugins**

Select **Chromatics.dll** and select **Add/Enable Plugin**.

[Corale.Colore.zip](https://github.com/roxaskeyheart/Chromatics/files/232783/Corale.Colore.zip)

**Comment by Blacke17** [comment]
Thank you so much! It's enabled now :)
