### ISSUE TITLE
Logitech G600 mouse will sometimes refuse to change color

### ISSUE THREAD

**Issue by CadeMan011** [roxaskeyheart/Chromatics#100]
Upon booting the main menu for the first time, the G600 color corresponds with the menu base color, but when the keyboard changes to default color, the mouse does not. Also occurs when entering Gold Saucer, or color changes due to weather. Only remedy I've found is to toggle Single Zone Mode on and off once, but it must be done again if user wishes to change mouse color to what the keyboard is. I have tried the Logitech troubleshooting guide, and it does not seem to fix the issue.

I really appreciate the work you guys do on the program.

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
