### ISSUE TITLE
Memory?

### ISSUE THREAD

**Issue by treymok** [roxaskeyheart/Chromatics#102]
Far as I can tell it loads fine and then I get this....

Chromatics exceeded maximum memory size. Pausing execution (Memory Size: 187804MB).

Nothing lights up...

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
