### ISSUE TITLE
Rgb strips (feature request)

### ISSUE THREAD

**Issue by andresblanco06** [roxaskeyheart/Chromatics#103]
I have some rgb strips behind my desk connected to my network and controlling using magic home app. Is there anyway to also control rgb strips?

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
