### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ghost** [roxaskeyheart/Chromatics#104]
I have two different Razer RGB devices and LIFX lightbulb. I think the issue is related to Razer.. Devices from Razer I have are Razer Deathadder Chroma and Razer Ornata, Deathadder requires Synapse 2. Ornata requires Synapse 3.

When I launch the program it gives me error "Call to native Chroma SDK function QueryDevice failed with error: Unknown: Unknown. (1167)"

Error log in the window that pops up is (And sorry that some of it is in finnish, not much I can do about that)
`Tämän sanoman lopussa on tietoja siitä, kuinka voit
ottaa käyttöön JIT-virheenkorjauksen tämän valintaikkunan sijasta.

************** Poikkeuksen teksti **************
Colore.Native.NativeCallException: Call to native Chroma SDK function QueryDevice failed with error: Unknown: Unknown. (1167) ---> System.ComponentModel.Win32Exception: Laite ei ole yhdistettynä
   --- Sisäisen poikkeuksen pinon jäljityksen loppu ---
   kohteessa Colore.Native.NativeApi.QueryDeviceAsync(Guid deviceId)
   kohteessa Colore.Implementations.KeyboardImplementation.get_IsDeathstalkerConnected()
   kohteessa Chromatics.DeviceInterfaces.RazerLib.ResetRazerDevices(Boolean deviceKeyboard, Boolean deviceKeypad, Boolean deviceMouse, Boolean deviceMousepad, Boolean deviceHeadset, Boolean deviceChromaLink, Color basecol) tiedostossa C:\Users\Dani\source\repos\roxaskeyheart\Chromatics\Chromatics\DeviceInterfaces\RazerInterface.cs:rivillä 358
   kohteessa Chromatics.Chromatics.GlobalResetDevices() tiedostossa C:\Users\Dani\source\repos\roxaskeyheart\Chromatics\Chromatics\DeviceInterfaces\GlobalInterface.cs:rivillä 347
   kohteessa Chromatics.Chromatics.InitDevicesGui() tiedostossa C:\Users\Dani\source\repos\roxaskeyheart\Chromatics\Chromatics\Controllers\GUIController.cs:rivillä 1369
   kohteessa Chromatics.Chromatics.MainThread() tiedostossa C:\Users\Dani\source\repos\roxaskeyheart\Chromatics\Chromatics\Chromatics.cs:rivillä 487
   kohteessa Chromatics.Chromatics.OnLoad(EventArgs e) tiedostossa C:\Users\Dani\source\repos\roxaskeyheart\Chromatics\Chromatics\Chromatics.cs:rivillä 268
   kohteessa System.Windows.Forms.Form.OnCreateControl()
   kohteessa System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   kohteessa System.Windows.Forms.Control.CreateControl()
   kohteessa System.Windows.Forms.Control.WmShowWindow(Message& m)
   kohteessa System.Windows.Forms.Control.WndProc(Message& m)
   kohteessa System.Windows.Forms.Form.WmShowWindow(Message& m)
   kohteessa System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Ladatut kokoonpanot **************
mscorlib
    Kokoonpanon versio: 4.0.0.0
    Win32-versio: 4.7.3416.0 built by: NET472REL1LAST_B
    Koodikanta: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Chromatics
    Kokoonpanon versio: 2.4.7.0
    Win32-versio: 2.4.7.0
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/Chromatics.exe
----------------------------------------
System.Windows.Forms
    Kokoonpanon versio: 4.0.0.0
    Win32-versio: 4.7.3324.0 built by: NET472REL1LAST_C
    Koodikanta: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Kokoonpanon versio: 4.0.0.0
    Win32-versio: 4.7.3416.0 built by: NET472REL1LAST_B
    Koodikanta: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Kokoonpanon versio: 4.0.0.0
    Win32-versio: 4.7.3190.0 built by: NET472REL1LAST_C
    Koodikanta: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Kokoonpanon versio: 4.0.0.0
    Win32-versio: 4.7.3362.0 built by: NET472REL1LAST_C
    Koodikanta: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
CommonServiceLocator
    Kokoonpanon versio: 2.0.2.0
    Win32-versio: 2.0.2.0
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/CommonServiceLocator.DLL
----------------------------------------
GalaSoft.MvvmLight.Extras
    Kokoonpanon versio: 5.4.1.0
    Win32-versio: 5.4.1.0
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/GalaSoft.MvvmLight.Extras.DLL
----------------------------------------
System.Runtime
    Kokoonpanon versio: 4.1.2.0
    Win32-versio: 4.6.25714.01
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/System.Runtime.DLL
----------------------------------------
netstandard
    Kokoonpanon versio: 2.0.0.0
    Win32-versio: 4.7.3190.0
    Koodikanta: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.ComponentModel
    Kokoonpanon versio: 4.0.1.0
    Win32-versio: 4.6.25714.01
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/System.ComponentModel.DLL
----------------------------------------
System.Threading
    Kokoonpanon versio: 4.0.11.0
    Win32-versio: 4.6.25714.01
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/System.Threading.DLL
----------------------------------------
System.Collections
    Kokoonpanon versio: 4.0.11.0
    Win32-versio: 4.6.25714.01
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/System.Collections.DLL
----------------------------------------
System.Reflection
    Kokoonpanon versio: 4.1.2.0
    Win32-versio: 4.6.25714.01
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/System.Reflection.DLL
----------------------------------------
System.Globalization
    Kokoonpanon versio: 4.0.11.0
    Win32-versio: 4.6.25714.01
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/System.Globalization.DLL
----------------------------------------
System.Linq
    Kokoonpanon versio: 4.1.2.0
    Win32-versio: 4.6.25714.01
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/System.Linq.DLL
----------------------------------------
Sharlayan
    Kokoonpanon versio: 5.0.0.0
    Win32-versio: 5.0.0.0
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/Sharlayan.DLL
----------------------------------------
System.Configuration
    Kokoonpanon versio: 4.0.0.0
    Win32-versio: 4.7.3324.0 built by: NET472REL1LAST_C
    Koodikanta: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Kokoonpanon versio: 4.0.0.0
    Win32-versio: 4.7.3190.0 built by: NET472REL1LAST_C
    Koodikanta: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Cyotek.Windows.Forms.ColorPicker
    Kokoonpanon versio: 1.0.0.0
    Win32-versio: 1.7.0.0
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/Cyotek.Windows.Forms.ColorPicker.DLL
----------------------------------------
System.Windows.Forms.resources
    Kokoonpanon versio: 4.0.0.0
    Win32-versio: 4.7.3190.0 built by: NET472REL1LAST_C
    Koodikanta: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_fi_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
LifxNet
    Kokoonpanon versio: 2.1.1.0
    Win32-versio: 2.1.1.0
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/LifxNet.DLL
----------------------------------------
Q42.HueApi
    Kokoonpanon versio: 3.6.2.0
    Win32-versio: 3.6.2.0
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/Q42.HueApi.DLL
----------------------------------------
Gma.System.MouseKeyHook
    Kokoonpanon versio: 5.6.130.0
    Win32-versio: 5.6.130.0
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/Gma.System.MouseKeyHook.DLL
----------------------------------------
CSharpAnalytics.Net45
    Kokoonpanon versio: 1.2.0.0
    Win32-versio: 1.2.0.0
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/CSharpAnalytics.Net45.DLL
----------------------------------------
Microsoft.VisualBasic
    Kokoonpanon versio: 10.0.0.0
    Win32-versio: 14.7.3190.0 built by: NET472REL1LAST_C
    Koodikanta: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
Microsoft.GeneratedCode
    Kokoonpanon versio: 1.0.0.0
    Win32-versio: 4.7.3190.0 built by: NET472REL1LAST_C
    Koodikanta: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Kokoonpanon versio: 1.0.0.0
    Win32-versio: 4.7.3190.0 built by: NET472REL1LAST_C
    Koodikanta: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Kokoonpanon versio: 1.0.0.0
    Win32-versio: 4.7.3190.0 built by: NET472REL1LAST_C
    Koodikanta: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Serialization
    Kokoonpanon versio: 4.0.0.0
    Win32-versio: 4.7.3324.0 built by: NET472REL1LAST_C
    Koodikanta: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    Kokoonpanon versio: 4.0.0.0
    Win32-versio: 4.7.3324.0 built by: NET472REL1LAST_C
    Koodikanta: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
Colore
    Kokoonpanon versio: 1.0.0.0
    Win32-versio: 1.0.0.0
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/Colore.DLL
----------------------------------------
Microsoft.CSharp
    Kokoonpanon versio: 4.0.0.0
    Win32-versio: 4.7.3190.0
    Koodikanta: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Kokoonpanon versio: 4.0.0.0
    Win32-versio: 4.7.3190.0
    Koodikanta: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Kokoonpanon versio: 0.0.0.0
    Win32-versio: 4.7.3416.0 built by: NET472REL1LAST_B
    Koodikanta: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
NLog
    Kokoonpanon versio: 4.0.0.0
    Win32-versio: 4.5.6.7874
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/NLog.DLL
----------------------------------------
System.Data
    Kokoonpanon versio: 4.0.0.0
    Win32-versio: 4.7.3260.0 built by: NET472REL1LAST_C
    Koodikanta: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.ServiceModel
    Kokoonpanon versio: 4.0.0.0
    Win32-versio: 4.7.3324.0 built by: NET472REL1LAST_C
    Koodikanta: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Kokoonpanon versio: 4.0.2.0
    Win32-versio: 4.6.26011.01
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/System.Runtime.InteropServices.RuntimeInformation.DLL
----------------------------------------
System.ValueTuple
    Kokoonpanon versio: 4.0.3.0
    Win32-versio: 4.6.26515.06
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/System.ValueTuple.DLL
----------------------------------------
Wooting.NET
    Kokoonpanon versio: 1.0.0.0
    Win32-versio: 1.0.0.0
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/Wooting.NET.DLL
----------------------------------------
System.Threading.Tasks
    Kokoonpanon versio: 4.0.11.0
    Win32-versio: 4.6.25714.01
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/System.Threading.Tasks.DLL
----------------------------------------
System.Net.Primitives
    Kokoonpanon versio: 4.0.11.0
    Win32-versio: 4.6.25714.01
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/System.Net.Primitives.DLL
----------------------------------------
System.Net.Sockets
    Kokoonpanon versio: 4.2.0.0
    Win32-versio: 4.6.26011.01
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/System.Net.Sockets.DLL
----------------------------------------
System.Runtime.Extensions
    Kokoonpanon versio: 4.1.2.0
    Win32-versio: 4.6.25714.01
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/System.Runtime.Extensions.DLL
----------------------------------------
System.Text.Encoding
    Kokoonpanon versio: 4.0.11.0
    Win32-versio: 4.6.25714.01
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/System.Text.Encoding.DLL
----------------------------------------
System.IO
    Kokoonpanon versio: 4.1.2.0
    Win32-versio: 4.6.25714.01
    Koodikanta: file:///C:/Program%20Files%20(x86)/Chromatics/System.IO.DLL
----------------------------------------
mscorlib.resources
    Kokoonpanon versio: 4.0.0.0
    Win32-versio: 4.7.3190.0 built by: NET472REL1LAST_C
    Koodikanta: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_fi_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** JIT-virheenkorjaus **************
JIT-virheenkorjauksen käyttöönotto edellyttää, että tämän
sovelluksen tai koneen kokoonpanon määritystiedostossa (Machine.config)
on jitDebugging-määritys system.windows.forms-osassa.
Virheenkorjaus on myös oltava käytössä sovellusta
käännettäessä.

Esimerkiksi:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Kun JIT-virheenkorjaus on käytössä, käsittelemättömät poikkeukset
lähetetään koneessa rekisteröityyn JIT-virheenkorjaukseen
eikä niitä käsitellä tässä valintaikkunassa.

`

**Comment by cg-** [comment]
I have the same error popping up. I have a Razer Cynosa, Naga Hex 2 on Synapse 3, and Razer Man O' War on Synapse 2.

Here's the messages:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
Colore.Native.NativeCallException: Call to native Chroma SDK function QueryDevice failed with error: Unknown: Unknown. (1167) ---> System.ComponentModel.Win32Exception: The device is not connected
   --- End of inner exception stack trace ---
   at Colore.Native.NativeApi.QueryDeviceAsync(Guid deviceId)
   at Colore.Implementations.KeyboardImplementation.get_IsDeathstalkerConnected()
   at Chromatics.DeviceInterfaces.RazerLib.ResetRazerDevices(Boolean deviceKeyboard, Boolean deviceKeypad, Boolean deviceMouse, Boolean deviceMousepad, Boolean deviceHeadset, Boolean deviceChromaLink, Color basecol) in C:\Users\Dani\source\repos\roxaskeyheart\Chromatics\Chromatics\DeviceInterfaces\RazerInterface.cs:line 358
   at Chromatics.Chromatics.GlobalResetDevices() in C:\Users\Dani\source\repos\roxaskeyheart\Chromatics\Chromatics\DeviceInterfaces\GlobalInterface.cs:line 347
   at Chromatics.Chromatics.InitDevicesGui() in C:\Users\Dani\source\repos\roxaskeyheart\Chromatics\Chromatics\Controllers\GUIController.cs:line 1369
   at Chromatics.Chromatics.MainThread() in C:\Users\Dani\source\repos\roxaskeyheart\Chromatics\Chromatics\Chromatics.cs:line 487
   at Chromatics.Chromatics.OnLoad(EventArgs e) in C:\Users\Dani\source\repos\roxaskeyheart\Chromatics\Chromatics\Chromatics.cs:line 268
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3416.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Chromatics
    Assembly Version: 2.4.7.0
    Win32 Version: 2.4.7.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/Chromatics.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3416.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
CommonServiceLocator
    Assembly Version: 2.0.2.0
    Win32 Version: 2.0.2.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/CommonServiceLocator.DLL
----------------------------------------
GalaSoft.MvvmLight.Extras
    Assembly Version: 5.4.1.0
    Win32 Version: 5.4.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/GalaSoft.MvvmLight.Extras.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.1.2.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.Runtime.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 4.0.1.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.ComponentModel.DLL
----------------------------------------
System.Threading
    Assembly Version: 4.0.11.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.Threading.DLL
----------------------------------------
System.Collections
    Assembly Version: 4.0.11.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.Collections.DLL
----------------------------------------
System.Reflection
    Assembly Version: 4.1.2.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.Reflection.DLL
----------------------------------------
System.Globalization
    Assembly Version: 4.0.11.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.Globalization.DLL
----------------------------------------
System.Linq
    Assembly Version: 4.1.2.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.Linq.DLL
----------------------------------------
Sharlayan
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/Sharlayan.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Cyotek.Windows.Forms.ColorPicker
    Assembly Version: 1.0.0.0
    Win32 Version: 1.7.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/Cyotek.Windows.Forms.ColorPicker.DLL
----------------------------------------
LifxNet
    Assembly Version: 2.1.1.0
    Win32 Version: 2.1.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/LifxNet.DLL
----------------------------------------
Q42.HueApi
    Assembly Version: 3.6.2.0
    Win32 Version: 3.6.2.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/Q42.HueApi.DLL
----------------------------------------
Gma.System.MouseKeyHook
    Assembly Version: 5.6.130.0
    Win32 Version: 5.6.130.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/Gma.System.MouseKeyHook.DLL
----------------------------------------
CSharpAnalytics.Net45
    Assembly Version: 1.2.0.0
    Win32 Version: 1.2.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/CSharpAnalytics.Net45.DLL
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
Colore
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/Colore.DLL
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.3416.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
NLog
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.6.7874
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/NLog.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 4.0.2.0
    Win32 Version: 4.6.26011.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.Runtime.InteropServices.RuntimeInformation.DLL
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.3.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.ValueTuple.DLL
----------------------------------------
Wooting.NET
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/Wooting.NET.DLL
----------------------------------------
System.Threading.Tasks
    Assembly Version: 4.0.11.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.Threading.Tasks.DLL
----------------------------------------
System.Net.Primitives
    Assembly Version: 4.0.11.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.Net.Primitives.DLL
----------------------------------------
System.Net.Sockets
    Assembly Version: 4.2.0.0
    Win32 Version: 4.6.26011.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.Net.Sockets.DLL
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 4.1.2.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.Runtime.Extensions.DLL
----------------------------------------
System.Text.Encoding
    Assembly Version: 4.0.11.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.Text.Encoding.DLL
----------------------------------------
System.IO
    Assembly Version: 4.1.2.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files%20(x86)/Chromatics/System.IO.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by logicallysynced** [comment]
Please join our Discord server where you can download the latest beta version for Shadowbringers compatibility.


https://discord.gg/sK47yFE

**Comment by tyllastarr** [comment]
I'm running the latest version of Chromatics and it CTDs on launch.  No error, just a crash to desktop.  I'm using Razer Chroma and connecting that to Hue bulbs.

**Comment by logicallysynced** [comment]
A CTD without message usually indicates that you are missing a prerequisite on your PC.  Do you have these installed?

https://docs.chromaticsffxiv.com/chromatics/getting-started/prerequisites

**Comment by tyllastarr** [comment]
> A CTD without message usually indicates that you are missing a prerequisite on your PC. Do you have these installed? https://docs.chromaticsffxiv.com/chromatics/getting-started/prerequisites
> […](#)
> On 21 Oct 2019, at 3:25 am, tyllastarr ***@***.***> wrote: ﻿ I'm running the latest version of Chromatics and it CTDs on launch. No error, just a crash to desktop. I'm using Razer Chroma and connecting that to Hue bulbs. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

I'll have to try reinstalling those.  I'll let you know whether it works or not.

EDIT: Nope, still doesn't work.  CTD right after it says "waiting for game launch"

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
