### ISSUE TITLE
Parse Error (Index outside bounds w/ overflow)

### ISSUE THREAD

**Issue by bbeenn1** [roxaskeyheart/Chromatics#106]
Chromatics Version 2.5.3
- - - - - - - - - -
Three errors, can't seem to track one down currently at all, due to a lack of information about what is throwing the message: 
```
Error: Object reference not set to an instance of an object.
```
If anyone has any information about this one so I can track it down I would appreciate it.
- - - - - - - - - -
```
Parse Error: Index was outside the bounds of the array.
Internal Error:    at Chromatics.Chromatics.ProcessFfxivData() in C:\Users\Dani\source\repos\roxaskeyheart\Chromatics\Chromatics\FFXIVInterfaces\FFXIVInterface.cs:line 7276
```
This message occurred frequently while playing, as I have several triggers configured in ACT.
Upon searching the cs file, this is likely due to ACT using the "Triggernometry" plugin, which extends Custom Triggers without actually being a custom trigger.

Simplest workaround for me would be to disable the "Flash on Custom Trigger" option. 
I will update this next time I am able to play if it resolves this issue.
- - - - - - - - - -
```
Parse Error: Arithmetic operation resulted in an overflow.
Internal Error:    at System.Convert.ToInt64(Double value)
   at Chromatics.Chromatics.ProcessFfxivData() in C:\Users\Dani\source\repos\roxaskeyheart\Chromatics\Chromatics\FFXIVInterfaces\FFXIVInterface.cs:line 3693
```
This one seems to be related to my Razer Naga Trinity mouse somehow, but I do not know what part would be causing issues.

I will disable the mouse zones one at a time to see which is causing the trouble and report back if it stops appearing.
- - - - - - - - - -
The exported log should be attached.
(I trimmed the duplicate Object reference & 7276 lines out)

[chromaticsdebug_6526682019.txt](https://github.com/roxaskeyheart/Chromatics/files/3470758/chromaticsdebug_6526682019.txt)

**Comment by bbeenn1** [comment]
With Razer SDK unloaded, and Mouse settings disabled, the parse error remains.
This is so far only when playing DNC, and is a constantly reoccurring message that can interfere with movement.

Confirmed "Flash on Custom Trigger" was clear, cleared Chromatic's cache, disabled triggernometry, removed the indicated file, launched Chromatics with right-click->Run as administrator.
All I have to do to get the error to start spamming is to enter any combat on DNC, even only using auto-attack starts the issue. 
Everything was working fine (from what I could tell) until I picked up dnc this week.

- edited to include more information after asking on Discord
https://discordapp.com/channels/334196655131721741/334198558091902976/608879341312409610
and
https://discordapp.com/channels/334196655131721741/334198558091902976/608920708663345173

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
