### ISSUE TITLE
Aurora Unified Keyboard integration support

### ISSUE THREAD

**Issue by chewston** [roxaskeyheart/Chromatics#107]
I noticed that for Chromatics, I have to force support for Logitech on the G910. I am using Aurora at this time because they have some really nice customizable options, they support multiple games outside of FF XIV but the support for FFXIV is broken at this time. Chromatics doesn't have the level of customization that Aurora has, I'd like to suggest support to have them work in unison. I can't say if it's really a bug or not, and who is at fault but considering that when Chromatics forces itself into Logitech's DLL, it breaks Aurora. I can't use any of my lighting stuff on Autora until I restart my system.

I really like what you guys do, that you have access to FFXIV's pointers in Chromatics but I am shooting in the dark for some kind of support to have both of them together, in some fashion. I would do it myself but I don't have enough knowledge to say begin to work support for it.

I already spoke with them on their end, they can't do anything but force the DLL, too. Which means your stuff would break, too, however for some reason it doesn't work on theirs. So I guess I'm just asking for collab on both ends, since both your applications are seemingly working on the same thing, but yours is more specialized towards one game.

Here's the link to their GitHub. 

https://github.com/antonpup/Aurora

**Comment by chewston** [comment]
I'd like to add that, the Aurora's support for XIV isn't something custom. It's using the default Logitech wrapper profile that was made by XIV dev team. It just doesn't do it with Aurora, the default profile in Ghub/LGS works fine.

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
