### ISSUE TITLE
Feedback/Features suggestions

### ISSUE THREAD

**Issue by mgrenier25** [roxaskeyheart/Chromatics#108]
I have been using this for a few weeks on my new build, it is pretty awesome.
It was not really straightforward to set up, I got it working somehow but I am still having some minor issues.  

I am using a Razer Goliathus extended mousepad, it does not register in the devices/mousepad section, it is zone 1 in other devices instead, same as my corsair h115 liquid cooler, changing one affects the other.

A similar issue would be zone 2 which controls Asus aura motherboard lights and the aura header, all at the same time, I cannot change them individually like I would in aura software.

I am also using a Corsair Ironclaw rgb wireless mouse, zone 1 in device/mouse section controls lighting in 2 zones at the same time

How does device detection happens? Maybe a suggestion, would it be possible to list devices under their respective sdk?

Is there any iCue profile file I can edit for keyboard? I would like to change the color of some macro keys and I don't see a way to do it within Chromatics. Maybe suggestion #2, would it be possible to use the proprietary softwares profile files to handle the infinite keyboard/mouse/headsets/mousepads possibilities? 

Some presets or custom lighting profiles would be awesome, like having a dungeon lighting mode, a crafting lighting mode, etc. Hotkeys swappable or that could swap from an in-game trigger like entering an instanced zone, or changing class or jobs.

Having this support more than one game would also be awesome

I will be happy to provide logs if you need them, keep up the good work

**Comment by mgrenier25** [comment]
Not working since last iCue update

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
