### ISSUE TITLE
Razer devices refuse to change colour

### ISSUE THREAD

**Issue by VCKing101** [roxaskeyheart/Chromatics#109]
unsure if has been reported before and cannot find any solution however none of the lighting effects are working anymore. It definitely attaches to FFXIV fine, seems to just be a Razer issue
Log is showing this and constantly adds the same thing over and over. 

Attempting Attach..
DX11 Initiated
Attached to FFXIV
Game Running
Error: Object reference not set to an instance of an object.
Error: Object reference not set to an instance of an object.
Error: Object reference not set to an instance of an object.
Error: Object reference not set to an instance of an object.
Error: Object reference not set to an instance of an object.
Error: Object reference not set to an instance of an object.

**Comment by VCKing101** [comment]
I should add this at the start of it

Starting Chromatics Version 2.5.3
Searching for devices.chromatics..
Attempting to load devices.chromatics..
devices.chromatics loaded.
Searching for settings.chromatics..
Attempting to load settings.chromatics..
settings.chromatics loaded.
Searching for mappings.chromatics..
Attempting to load mappings.chromatics..
mappings.chromatics loaded.
Attempting to load Razer SDK..
Razer SDK Loaded (6.0.0.5)

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
