### ISSUE TITLE
MP Tracker doesn't update lighting

### ISSUE THREAD

**Issue by Luggs123** [roxaskeyheart/Chromatics#110]
On my Razer Ornata Chroma, setups that implement the MP Tracker will display full MP regardless of the player's true MP value. This is also not exclusive to a single job, as swapping between jobs at less than full MP does not rectify this problem.

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
