### ISSUE TITLE
Keypad Keybind

### ISSUE THREAD

**Issue by BenoitAnastay** [roxaskeyheart/Chromatics#111]
I was able to keybind this ÉÈÇ keys by making them uppper case in the hotbar loop 
[](https://github.com/BenoitAnastay/Chromatics/commit/6a8235752a479cc6ffdef4bb5fa1207457438cd1#r38119171)

But the keybind for F keys isn't recognised by the UI, I don't know how to catch the F keys in the UI, I'm not a GUI developper, but it does work well setting them up manually in the config file

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
