### ISSUE TITLE
Chromatics crashing for some reason

### ISSUE THREAD

**Issue by Specterd03** [roxaskeyheart/Chromatics#113]
I noticed that the program is crashing after a certain amount of time. I use Corsair's ICUE on a windows 10 platform. When I first got Chromatics, I never had any issue with it. 

All the same, I reinstalled Corsair ICUE, Chromatics and FF14. Still the same error.
[chromaticsdebug_182331352020.txt](https://github.com/roxaskeyheart/Chromatics/files/4623749/chromaticsdebug_182331352020.txt)

I attached a copy of the log for you to review. Not sure what to do about "overflow"

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
