### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ZeroV13** [roxaskeyheart/Chromatics#114]
I do not recall messing with anything other than ticking on some of the boxes in the settings.  Attached is the debug file.  This error occurs repeatedly sometimes without even interacting with the game, just having it open in the background.  Eventually once it has racked up enough instances of the error it crashes the app causing all chroma to go back to whatever the default is for desktop

[chromaticsdebug_1859192262020.txt](https://github.com/roxaskeyheart/Chromatics/files/4815116/chromaticsdebug_1859192262020.txt)

**Comment by Chadrolfsen** [comment]
did you ever get this resolved?  I'm having the same issue.

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
