### ISSUE TITLE
Unable to open

### ISSUE THREAD

**Issue by Alodith** [roxaskeyheart/Chromatics#115]
Whenever I open the application, it immediately closes. I have tried closing everything else but the issue still remains.

**Comment by Chadrolfsen** [comment]
did you ever get this resolved? I'm having the same issue

**Comment by magrindell** [comment]
I have this issue as well

**Comment by Logarius23** [comment]
Same issue as well

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
