### ISSUE TITLE
Blinking keys: keybinds and job gauge

### ISSUE THREAD

**Issue by Reylak** [roxaskeyheart/Chromatics#116]
I understand Chromatics is heavily behind FFXIV patches, so this issue is most probably related to Chromatics being out-of-date.

Keyboard: Logitech G513
FFXIV in French language, v5.41

Keybound keys and job gauge blink abnormally in base mode "Job classes". The former blink between base color and keybind available color, and the latter blink between off and base color.

In general, job gauge does not work (does not change with job gauge in-game), including in "Static Color" mode. However, keybinds work fine in "Static Color" mode (i.e. no blinking, change color when out-of-range or proc).

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
