### ISSUE TITLE
Add updater source code

### ISSUE THREAD

**Issue by Reylak** [roxaskeyheart/Chromatics#117]
I noticed "Chromatics Updater" is ignored in .gitignore file, meaning the source code is missing and the VS solution fails to load the updater project.

Is this expected? Is the updater still used by Chromatics?

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
