### ISSUE TITLE
Chromatics keeps flashing keyboard when duty is found even after accepting it

### ISSUE THREAD

**Issue by Reylak** [roxaskeyheart/Chromatics#118]
Chromatics 2.5.6, keyboard Logitech G513

When a duty is found, the keyboard flashes. But it keeps flashing even after accepting and entering the duty. Restarting Chromatics stops this.

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
