### ISSUE TITLE
Doesn't run up start of windows

### ISSUE THREAD

**Issue by Talbuki** [roxaskeyheart/Chromatics#119]
Despite ticking start on windows setting isn't saved so i have to manually keep start Chromatic.

**Comment by Boedicia** [comment]
+1

I am also getting this issue.

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
