### ISSUE TITLE
will support Korean Version ?

### ISSUE THREAD

**Issue by MCASE28** [roxaskeyheart/Chromatics#12]
i like use chromatic on Korean version, but Chromaitc 1.9.0 can't read Korean Local name and Weather name.. with gold saucer Vegas mode! ...but FC / LS Chat, Target DPS is working.

**Comment by logicallysynced** [comment]
If you can tell me what the korean words/characters for the zones, weather, etc. are according to ACT (e.g. what ACT displays as the zone name in its header bar), I can copy them into the Chromatics code. I won't be able to test it but it should work that way.
