### ISSUE TITLE
Color freeze while game is running

### ISSUE THREAD

**Issue by Volondil** [roxaskeyheart/Chromatics#120]
My keyboard change color when entering the world ingame, but nothing happen after this.

Starting Chromatics Version 2.5.6
Searching for devices.chromatics..
Attempting to load devices.chromatics..
devices.chromatics loaded.
Searching for settings.chromatics..
Attempting to load settings.chromatics..
settings.chromatics loaded.
Searching for mappings.chromatics..
Attempting to load mappings.chromatics..
mappings.chromatics loaded.
Attempting to load Razer SDK..
Razer SDK Loaded (6.0.0.5)
Attempting to load Corsair SDK..
CUE SDK Loaded (3.0.301/3.38.61)
Game Language set to French.
No new updates currently available.
Waiting for Game Launch..
Attempting Attach..
DX11 Initiated
Attached to FFXIV
Main Menu is still active.
Game Running

my polling interval is set to 300 ms and my region keyboard is set to AZERTY.
I disabled all SDK that i 'm not using (i use only razer synapse 2 for keyboard and corsair icue 3 for mouse).

I uninstalled/reinstalled many times synapse razer but nothing changed. I precise that i use synapse 2 instead of version 3 because my keyboard (Deathstalker chroma) is not recognized by the version 3.

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
