### ISSUE TITLE
does not install

### ISSUE THREAD

**Issue by bellexandria** [roxaskeyheart/Chromatics#121]
![image](https://user-images.githubusercontent.com/39638114/143187173-d6da1fa5-7c02-417a-99b7-9710de95e53d.png)

**Comment by magrindell** [comment]
I have this issue as well

**Comment by Pyro-Soul** [comment]
Got the same issue here, even before endwalker release.

**Comment by logicallysynced** [comment]
Just to be sure, you guys aren’t installing the plugin found in the ACT plugin list are you? That plugin is Chromatics V1 and has been inactive for years now (ACT won’t let me remove it for some reason).

You don’t need ACT to run Chromatics as of V2 and you can download the latest version from the releases page on this GitHub or https://chromaticsffxiv.com/

There is an optional ACT plugin included with V2 which brings ACT functionality into Chromatics, but it is completely optional and packaged with the new files - not downloaded from within ACT.

**Comment by frogcrush** [comment]
I can confirm this is the issue when trying to use the ACT plugin version.

**Comment by logicallysynced** [comment]
I have submitted a request to ACT developers to remove the plugin from the list.
