### ISSUE TITLE
Naga X only lights up the mouse wheel. (Only Zone 2 does anything)

### ISSUE THREAD

**Issue by Quan7um64** [roxaskeyheart/Chromatics#122]
Also, disabling the mouse lighting with the Naga X does nothing, and the lighting on the mouse wheel stays.

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
