### ISSUE TITLE
Primary Keyboard Lights have stopped working in endwalker

### ISSUE THREAD

**Issue by Xaiamas** [roxaskeyheart/Chromatics#123]
On Razer Keyboards, the main section of the keyboard, including WASD no longer illuminates when starting Chromatics

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
