### ISSUE TITLE
job gauge issue

### ISSUE THREAD

**Issue by manulcorp** [roxaskeyheart/Chromatics#124]
game language: korean
then
enable job gauge effects

Parse Error: 개체 참조가 개체의 인스턴스로 설정되지 않았습니다.
Internal Error:    위치: Chromatics.Chromatics.ImplementJobGauges(List`1 statEffects, Color baseColor, ActionResult hotbars, JobResourceResult Cooldowns) 파일 C:\Users\Dani\source\repos\roxaskeyheart\Chromatics\Chromatics\FFXIVInterfaces\FFXIVJobGauges.cs:줄 2642
   위치: Chromatics.Chromatics.ProcessFfxivData() 파일 C:\Users\Dani\source\repos\roxaskeyheart\Chromatics\Chromatics\FFXIVInterfaces\FFXIVInterface.cs:줄 7023

**Comment by manulcorp** [comment]
and advanced combat track issue

***** 2022-02-03T13:19:01 - Notification
Event Handler Unhandled Exceptions
In the last minute, these plugins caused exceptions in event handlers:

ChromaticsACT, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null [4 time(s)]

***** 2022-02-03T13:22:29 - Enabling plugin: E:\game\FF14 HAERUBOT\Chromatics\ChromaticsACT.dll
***** 2022-02-03T13:22:29 - Initialized ChromaticsACT, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
***** 2022-02-03T13:24:01 - BeforeLogLineRead event
21|2022-02-03T13:24:01.4510000+09:00|1020054D|도레|1D4F|졸트|400A8E71|불꽃송곳니 지휘관|750003|2A70000|3033D|BA8000|1B|1D4F8000|0|0|0|0|0|0|0|0|0|0|3500|26943|0|10000|0|1000|539.3301|-32.08978|7.599619|-0.7195919|5724|6467|8600|10000|0|1000|542.1669|-32.85871|7.599619|-1.306102|0060FC85|0|ef7ce11e207051325a369bbacc8af864
System.InvalidOperationException: 컬렉션이 수정되었습니다. 열거 작업이 실행되지 않을 수도 있습니다.
   위치: System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   위치: System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   위치: System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   위치: System.Linq.Enumerable.Sum(IEnumerable`1 source)
   위치: FFXIV_ACT_Plugin.ACT_UIMods.<>c.<UpdateACTTables>b__18_81(AttackType Data)
   위치: FFXIV_ACT_Plugin.ACT_UIMods.<>c.<UpdateACTTables>b__18_84(DamageTypeData Data)
   위치: ChromaticsACT.ChromaticsACTPlugin.OnBeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo)
   위치: Advanced_Combat_Tracker.FormActMain.ParseRawLogLine(Boolean isImport, DateTime ParsedLogTime, String LogLine, String CompanionLogName)

   위치: Advanced_Combat_Tracker.FormActMain.WriteExceptionLog(Exception ex, String MoreInfo)
   위치: Advanced_Combat_Tracker.FormActMain.ParseRawLogLine(Boolean isImport, DateTime ParsedLogTime, String LogLine, String CompanionLogName)
   위치: Advanced_Combat_Tracker.FormActMain.ReadLog()
   위치: System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   위치: System.Threading.ThreadHelper.ThreadStart()
*****


In my opinion, "Game Language: Korean" part seems to cause errors overall.

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
