### ISSUE TITLE
Installer kicks off then stops and runs in background

### ISSUE THREAD

**Issue by 3v1lb1t** [roxaskeyheart/Chromatics#125]
I can't get Chromatics to install. The installer kicks off with UAC then just hangs in the background. Doesn't stop until I end task, if I don't end task no matter how long after I initially kick it off, I get the error attached. 
![error](https://user-images.githubusercontent.com/36797011/161433678-b4b4813a-dd4e-4001-a282-16717ff0d500.png)

**Comment by Nox13last** [comment]
Same.
My Malwarebytes AntiMalware is heuristically determining that the installer is **Malware.Heuristic.1008**. This seems to mean that the installer _looked at it funny_, and it's freaking out and quarantining it for no other reason.
Despite un-quarantining it, it still refused to run. I **did** find a solution, though, which might work for you.

Download an old version from the Releases list. I downloaded 2.4.6, and the installer went fine.
Then run the program that comes out (you may have to run it manually), and let it self-update to the latest (which seems to be 2.7.2 at the time of writing)

**Comment by logicallysynced** [comment]
I’ve been using InstallForge to package the installer for pretty much the entire 2.X series of the app.

Can you guys use the portable version instead?

**Comment by Nox13last** [comment]
> I’ve been using InstallForge to package the installer for pretty much the entire 2.X series of the app.
> 
> Can you guys use the portable version instead?

Downloading from [the main download page](https://chromaticsffxiv.com/download.html), Portable 2.7.1 seems to run fine. It also immediately wanted to update to 2.7.2.
For repro, I downloaded the Installer version (still 2.7.1, still from the above page) and attempted to run it. It has once again created a zombie process that must be terminated through Task Manager, and does not appear to have installed anything.

**Comment by CharlieDelune** [comment]
Having this same issue, have to imagine it has something to do with Win 11

**Comment by Nox13last** [comment]
Using Windows 10 here.

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
