### ISSUE TITLE
Chromatics stuck on Main Menu Still Active

### ISSUE THREAD

**Issue by 3v1lb1t** [roxaskeyheart/Chromatics#126]
I have tried a few different troubleshooting steps, made sure nothing might have been blocking the communication. Chromatics sees the launch of the game and goes into Main Menu mode. It doesn't get out of that mode when I am in game. 

![image](https://user-images.githubusercontent.com/36797011/163720144-38c63f5f-1d28-40ca-b6bf-f617b2d3fd06.png)

**Comment by thisischrys** [comment]
I am experiencing this since the latest patch.

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
