### ISSUE TITLE
Very high CPU ussage when running

### ISSUE THREAD

**Issue by RagingFlames** [roxaskeyheart/Chromatics#127]
Fairly basic issue, chromatics is using a LOT of CPU time when I have it running. I'm more than willing to help collect more information on this problem but right now I'm not really sure where to start.
OS: Windows 10 64 bit
RAM: 48 GB
CPU: 5800x
GPU: 6700xt

![image](https://user-images.githubusercontent.com/28068199/167953531-0cf07595-5724-45f4-a8aa-2bfc5af6d223.png)

**Comment by benphantom41** [comment]
This happens to me as well. Only gets that high CPU after I close FF14 and I close the main window.

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
