### ISSUE TITLE
Followed directions, still not working.

### ISSUE THREAD

**Issue by immaninja** [roxaskeyheart/Chromatics#13]
Attached is the error I am getting when trying to install the app. I unblocked the file and still no luck. 
https://gyazo.com/ca85bc8a305de8335c5476c9b024b0ca

**Comment by logicallysynced** [comment]
I can see you are opening a dependency instead of the main plugin manually. Can you try adding Chromatics.dll instead of Colore. It should be in the folder above lib.

**Comment by immaninja** [comment]
Not sure if I'm looking in the right location but this is all I can find
https://gyazo.com/f3a4a6bfb0079397ffa3ded6f65edf06

If there is an easier way to help you help let me know, I would think these screenshots isn't the best way to communicate.

**Comment by logicallysynced** [comment]
I think you downloaded the repository and not the latest release. Try and download from this link

https://github.com/roxaskeyheart/Chromatics/releases

It should be a zip file.

**Comment by immaninja** [comment]
GG it works great, thanks for all the help!
