### ISSUE TITLE
Chromatics crashes before it opens (Razer)

### ISSUE THREAD

**Issue by Logarius23** [roxaskeyheart/Chromatics#130]
Every time I run chromatics for FFXIV, it crashes before it even opens up to attach to the game. The logo appears in the bottom right task bar but when you swipe over to it, it disappears. I haven't been able to use chromatics for ffxiv for some time now. I do not have Windows 11 yet so I'm not sure if I need to upgrade to that...

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
