### ISSUE TITLE
Major input lag

### ISSUE THREAD

**Issue by Oldwargoat39** [roxaskeyheart/Chromatics#133]
I have been noticing when Chromatics is running I am getting some serious input lag from movement to using Hotbar actions sometimes it's a small amount other times it's 3-5 seconds before actions are used. But the movement is either laggy or rubber bands after I stop pressing the movement keys.
Enclosed is the debug report maybe something on my end or it might be something with Chromatics that is doing it.
[chromaticsdebug_2021630122022.txt](https://github.com/roxaskeyheart/Chromatics/files/10326172/chromaticsdebug_2021630122022.txt)

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
