### ISSUE TITLE
ZipExtractor hangs waiting for the parent application to close.

### ISSUE THREAD

**Issue by thakyZ** [roxaskeyheart/Chromatics#145]
The updater executable `ZipExtractor.exe` seems to wait forever for the parent application to close, thus I had to run it via getting the command line options it used and running it manually my self.

**Comment by logicallysynced** [comment]
This is a known issue right now as Chromatics can take up to 30 seconds to fully dispose. I have improved this to about 10 seconds in version 3.0.0.9 but it still needs work.

**Comment by thakyZ** [comment]
Well it worked flawlessly now, thanks!
