### ISSUE TITLE
Corsair Utility Engine not recognized in devices

### ISSUE THREAD

**Issue by Siluss** [roxaskeyheart/Chromatics#16]
Hello,

I'm interested in using chromatics in ACT for EQ2. I downloaded and installed chromatics manually. I unblocked everything before I installed. The chromatics tab in ACT shows up and when i go to the devices tab, none of the boxes are checked and when I scan for devices I get:

"CUE (Corsair Utility Engine) is currently not running or not installed. Please install or run the program and restart ACT to enable Corsair Support."

I have CUE installed. I have it running. Ive tried downloading the sdk from corsair website and manually copied the bin folder containing the cuesdk.x64_201(2,3,5).dll files. I also tried copying those same dll files in the main CUE folder. The path that I have CUE installed is:

C:\Program Files\Corsair\CUE

Using the plugin installer from ACT gives me Corale.Colore.dll which gives me an assembly error if I try to enable. 

I am running Windows 10 pro 64 bit. I have the latest version of ACT and Chromatics. I am using a Corsair k95 RGB keyboard. Ive tried everything I can possibly think of and more than Ive listed here. Please help! Thanks.

**Comment by LiteMorgan** [comment]
Can also report the same issue. Using:
- Windows 10 Pro, 64 bit
- ACT 3.3.0
- CUE 2.6.70
- Chromatics 1.9.0

**Comment by tinysatsuki** [comment]
I'm having the same issue with my k95 RGB board. CUE is running and "Enable SDK" is checked in the CUE. Lights on my Razer Naga Chroma are working just fine.

Windows 7 Pro 64 bit
ACT 3.3.0
CUE 2.8.70
Chromatics 1.9.2

Any help would be appreciated!

Here's what the log says:

> Chromatics Log (1/5/2017 3:09:30 AM):
Logitech SDK Disabled. 
No Corsair devices detected. 
Razer SDK Detected. Attempting to Load.. 
Chromatics Config Loaded. 
Starting Chromatics.. 
Chromatics Plugin Started 
Logitech SDK Disabled. 
No Corsair devices detected. 
Razer SDK Detected. Attempting to Load.. 
CUE (Corsair Utility Engine) is currently not running or not installed. Please install or run the program and restart ACT to enable Corsair Support. 
Logitech Gaming Software is currently not running or not installed.Please install or run the program and restart ACT to enable Logitech Support.

**Comment by logicallysynced** [comment]
Since Corsair recently rebuilt their SDK, it is current incompatible with Chromatics. I am looking into re-writing the Corsair coding to allow compatibility again but there is no timeframe on this unfortunately. Sorry for the inconvenience :(

**Comment by Ihysoal** [comment]
Just posting this comment to show interest in an update for the newer CUE.

Edit: And oh hey, thanks for making something like this.

Edit: Just found out that CUE2 is a thing and I'm still using CUE and I might be getting an error not related to this.

**Comment by logicallysynced** [comment]
Updated to 1.9.3 to re-enable Corsair support. Please download and follow instructions as usual: https://github.com/roxaskeyheart/Chromatics/releases

I haven't been able to test this outside of the Corsair simulator so any feedback would be appreciated on device support. Since FFXIV is down for maintenance at the moment you should be able to get feedback from changing the **Default Device Color** tab.

**Comment by LiteMorgan** [comment]
Have reinstalled, the following messages came up:
"An unknown error occurred while trying to load the Corsair libraries. Corsair support will be disables. (Code 2)"
"Can't find the CUE-SDK at the expected location '_link to Program Files\Advanced Combat Tracker\x64\CUESDK_2015.dll_'"

Definitely got CUE installed, and the SDK mode turned on. Is there a file we have to move into place there?

**Comment by logicallysynced** [comment]
Make sure you have CUE 2 installed and not CUE 1 as its not compatible anymore.

Other than that you may need to copy the **CUESDK_2015.dll** file from the **/lib/** directory in the Chromatics zip to **Program Files\Advanced Combat Tracker\x64\**, creating the necessary folders along the way.

Additionally make sure to right-click and unblock any files (or the zip before extracting)

**Comment by LiteMorgan** [comment]
Perfect, that appears to be working for me! Thank you
