### ISSUE TITLE
unable to load plugin

### ISSUE THREAD

**Issue by moonboy1207** [roxaskeyheart/Chromatics#17]
![image](https://cloud.githubusercontent.com/assets/12956083/21102023/d03c4000-c041-11e6-899f-2f119686f574.png)
 I get this when using the repository form ACT and trying to manually load chrinatics

**Comment by moonboy1207** [comment]
![image](https://cloud.githubusercontent.com/assets/12956083/21113455/4961461a-c06f-11e6-9a02-7a801e77856c.png)
![image](https://cloud.githubusercontent.com/assets/12956083/21113468/4f32acfa-c06f-11e6-9221-597d6708884b.png)

**Comment by moonboy1207** [comment]
as you can see if I try to load chromatics it says Advanced combat tracker does not use this DLL I also tried older versions earlier and had the same issue

**Comment by logicallysynced** [comment]
Will investigate this and get back to you. Just to be sure are you running the latest version of ACT, FFXIV Parsing Plugin, Razer and have all the dependencies installed as referenced on the Chromatics main page?

**Comment by moonboy1207** [comment]
I belive I am up to date at all times with everything i got, razer is up to date, the ffxiv parsing plugin is up tom date, and Advanced combat tracker is up to date

**Comment by moonboy1207** [comment]
i only have razer and logitech installed however when it comes to the mouse/keyboard/headset stuff, I do not have anything form corsair do i still need the program

**Comment by entvex** [comment]
I have the same issue

**Comment by moonboy1207** [comment]
![image](https://cloud.githubusercontent.com/assets/12956083/21581637/18ee0bf8-d000-11e6-9a9e-64a0577a1aa3.png)

new error form the old one

**Comment by logicallysynced** [comment]
The Razer Chroma SDK has been updated so this plugin needs to be updated to match. I have actioned to do this asap but the holidays are delaying me a bit. Sorry for the inconvenience in the mean time~ >_<

**Comment by logicallysynced** [comment]
Updated to Version 1.9.2. Please download manually and try this version and let me know how it goes.

**Comment by logicallysynced** [comment]
Closing due to lack of response. Please open a new ticket if you're still experiencing issues.
