### ISSUE TITLE
Plugin Initialization Failed: The type initializer for 'CUE.NET.Native._CUESDK' threw an exception.

### ISSUE THREAD

**Issue by Ihysoal** [roxaskeyheart/Chromatics#18]
![image](https://cloud.githubusercontent.com/assets/124339/21978343/7d39c602-dbda-11e6-9693-25bc6cfe6f5b.png)

- Windows 8.1
- CUE 1.16.42
- Corsair Strafe RGB
- ACT 3.3.0

Tried updating CUE.NET.dll to latest version but to no avail. I can't find out if there's a log anywhere either.

I'll be trying some older versions of CUE.NET to see if I can get it to work.

**Comment by Ihysoal** [comment]
I just tested all CUE.NET versions, and it seems to throw the error with 1.02 and onwards. I'm going to use 1.01 for now to see if it works.

**Comment by logicallysynced** [comment]
I am currently working on re-enabling Corsair support in Chromatics as we speak.
It will be limited compared to that of Razer devices but should work nonetheless.

Expect to see it within the next hour or two.

**Comment by Ihysoal** [comment]
Woo!

**Comment by logicallysynced** [comment]
Updated to 1.9.3 to re-enable Corsair support. Please download and follow instructions as usual: https://github.com/roxaskeyheart/Chromatics/releases

**Important: Please remove all existing versions of Chromatics AND CUE.NET.dll before installing.**

I haven't been able to test this outside of the Corsair simulator so any feedback would be appreciated on device support. Since FFXIV is down for maintenance at the moment you should be able to get feedback from changing the **Default Device Color** tab.

**Comment by Ihysoal** [comment]
Thanks for the fast update :)

CUE1 (obviously?) broke with the update.

The following happened while trying to enable (I installed the plugin in %appdata%\Advanced Combat Tracker\Plugins) 

![image](https://cloud.githubusercontent.com/assets/124339/21983999/1fcb3fae-dbf4-11e6-9e2b-c4b9d74a6b88.png)

Easily solved by providing the DLL where it expects, after that seems to run fine.

It detects the device on startup, trying to do a rescan of devices will then bug out after giving two of the popups about CUE missing (only the first time) and make CUE2 unresponsive to the plugin. It's fine again after a restart of ACT.

Edit: Log of startup + rescan

> Logitech SDK Disabled. 
> Corsair SDK Detected. Attempting to Load.. 
> Initialized with x64-SDK 
> Corsair Keyboard Detected. 
> Chromatics Config Loaded. 
> Starting Chromatics.. 
> Chromatics Plugin Started 
> Logitech SDK Disabled. 
> Corsair SDK Detected. Attempting to Load.. 
> CUE (Corsair Utility Engine) is currently not running or not installed. Please install or run the program and restart ACT to enable Corsair Support. 
> No Corsair devices detected. 
> The Razer SDK (RzChromaSDK64.dll) Could not be found on this computer. Please install Synapse and restart ACT if you wish to use Chromatics with Razer devices. 
> CUE (Corsair Utility Engine) is currently not running or not installed. Please install or run the program and restart ACT to enable Corsair Support. 
> Logitech Gaming Software is currently not running or not installed.Please install or run the program and restart ACT to enable Logitech Support. 

Will try to extensively test when FFXIV is back online.

**Comment by logicallysynced** [comment]
It requires ACT to be restarted after installing for the first time. Should load automatically consistently after that first restart.

**Comment by Ihysoal** [comment]
Ah well, it seems to work on startup after the initial install and restart. The two things mentioned above still stand: the odd DLL requirement from the executable's folder and device support breaking after a rescan.

Although I'm still not sure if CUE1 breaking is intentional.

**Comment by logicallysynced** [comment]
CUE2 is required now as it is the latest version, so CUE1 is unsupported now.

The DLL requirement is due to you having ACT installed in a different location than the default Program Files location. Normally Chromatics would auto-install that file on initialisation.

I will have to look into the bug from Rescanning, so in the mean time maybe restarting ACT to rescan might be a good work around?

**Comment by Ihysoal** [comment]
>Normally Chromatics would auto-install that file on initialisation.

Doesn't do that unfortunately.

>I will have to look into the bug from Rescanning, so in the mean time maybe restarting ACT to rescan might be a good work around?

Of course, and I'll just not rescan devices pointlessly.

**Comment by logicallysynced** [comment]
Auto-install it to the Program Files directory that is, but since you have ACT installed elsewhere it wasn't able to deploy the DLL correctly. I'll have to look into a way around that also.

**Comment by logicallysynced** [comment]
Closing due to redesigned [2.0.0](https://chromaticsffxiv.com/) release.
