### ISSUE TITLE
Patch 3.5 problems

### ISSUE THREAD

**Issue by Ihysoal** [roxaskeyheart/Chromatics#19]
Hey, well, I found out a few issues now that the FFXIV plugin is updated and I can actually get parses again.

- DPS threshold doesn't seem to work without enmity change
- Vegas mode doesn't work.
- When leaving combat (possibly due to changing zones during combat, thanks FC house), will revert to default state. After that any trigger will revert to DPS threshold colour instead of the default. A zone switch will restore to default again but any trigger will make it go back to DPS threshold again.

If you want to play 3.5 instead of fixing things for the one guy that probably uses it with CUE, I would understand too.

Edit: Perhaps I should've opened seperate issues for each of them, it's up to you I guess.

**Comment by logicallysynced** [comment]
Most of these issues may be due to the fact that ACT is currently not compatible with 3.5. They should release an update soon which will hopefully resolve some of those issues.

For Vegas Mode, that is unfortunately a Razer feature, I'll have to investigate how to port that to Corsair.

**Comment by Ihysoal** [comment]
https://github.com/ravahn/FFXIV_ACT_Plugin/releases

The ACT plugin updates quite fast. I suppose it could still have bugs in it, but it went from completely disfunctional to seemingly fine in that update.
