### ISSUE TITLE
"Call to the native SDK function Init failed with error: Unknown: Unknown. (1060)"

### ISSUE THREAD

**Issue by MamaSaucy** [roxaskeyheart/Chromatics#20]
I've tried to run ACT as admin and without. I tried to use this before the new ffxiv patch and got the same error every time i try to install it. II had Avast anti-virus but uninstall it and it still won't install. However it installs fine on my laptop.

**Comment by logicallysynced** [comment]
Can you step through exactly how you went about installing this? Also have you got all the pre-requisites installed?

**Comment by MamaSaucy** [comment]
I initially tried to follow the manual steps of getting zip unblocking then unzipping and opening ACT and adding plugin. Then I tried the automatic way through the "get plugin" option in ACT and chose Chromatics but both result in the same error.

I tried to install the .NetFrame but it tells me
Microsoft .NET Framework 4.5 is already a part of this operating system.  You do not need to install the .NET Framework 4.5 redistributable.

Same or higher version of .NET Framework 4.5 has already been installed on this computer.

and when i try to install the vc_redist version 14.0.23026 it tells me another version exist, which is true i have version 14.0.24210

**Comment by logicallysynced** [comment]
Can you send me a screenshot of this error message?

**Comment by MamaSaucy** [comment]
![chromatic errror 2](https://cloud.githubusercontent.com/assets/5841198/22093071/3db5d80a-ddc8-11e6-9930-8c91be227eab.PNG)

well this is what im getting now from the "get plugin" method this is how the original error looks when i do it the manuel way
 
![chromatic error 1](https://cloud.githubusercontent.com/assets/5841198/22093093/73a2a704-ddc8-11e6-866b-a8e42954b0f3.PNG)

**Comment by logicallysynced** [comment]
Are you running the latest Razer Synapse version and have Razer Chroma SDK installed?

**Comment by MamaSaucy** [comment]
I have the latest Razer Synapse version 2.20 not sure how to check if i actually have the SDK. the guide said it installs with Synapse so im guessing i have it. maybe.

**Comment by logicallysynced** [comment]
I'll have to get back to you on this, I'm not sure what exactly could be causing this if you've unblocked everything and got everything installed.

Maybe double check all the files (including the ones in the /lib/ folder are unblocked.

**Comment by MamaSaucy** [comment]
okie dokie i shall be waiting patiently thanks for looking into it!

**Comment by logicallysynced** [comment]
My power is out at the moment after a storm so I can't properly look into this right now, however can you find your ACT log file, which I believe is in **C:/Users/You/AppData/Roaming/ACT/**

Then delete it, restart ACT and try to load the plugin manually (check the unblocks again first), then post the log file here?

**Comment by MamaSaucy** [comment]
for whatever reason the txt and .docx would not go through here but here is a pdf


[Advanced Combat Tracker.pdf](https://github.com/roxaskeyheart/Chromatics/files/717692/Advanced.Combat.Tracker.pdf)

**Comment by logicallysynced** [comment]
**Assigned to fix in 2.0**

**Comment by logicallysynced** [comment]
Closing due to redesigned [2.0.0](https://chromaticsffxiv.com/) release.
