### ISSUE TITLE
Looking for Razer Beta Testers for Chromatics 2.0

### ISSUE THREAD

**Issue by logicallysynced** [roxaskeyheart/Chromatics#21]
Hi all,

I am in need of some beta testers to test the new release of Chromatics.
Currently I am looking for Razer device owners but will soon also be looking for Corsair and Logitech.

This new version of Chromatics is not reliant on ACT and includes a lot of new features, especially for Razer BlackWidow Chroma users.

Please reply to this issue or send me an email at technicaldaniel@gmail.com if you are interested~ 👍

**Comment by moonboy1207** [comment]
um I can take it on I use razer naga and Razer firefly i also have a razer deathstalker ultimate I also have a Logitech g600, Logitech 619, logitech g13

**Comment by tiagomartines11** [comment]
Email sent :)

**Comment by reave** [comment]
If you still need support, I can help. I have a Blackwidow Chroma v2
