### ISSUE TITLE
Chromatics Fails to start with Razer Devices

### ISSUE THREAD

**Issue by moonboy1207** [roxaskeyheart/Chromatics#22]
![image](https://cloud.githubusercontent.com/assets/12956083/22561701/f3aa6c12-e93e-11e6-96be-70b9e977c7bd.png)

I have the SDK installed the plugin loaded for logitech devices but not for razer and when I went to restart it completely failed

**Comment by logicallysynced** [comment]
Closing due to redesigned [2.0.0](https://chromaticsffxiv.com/) release.
