### ISSUE TITLE
Main Menu still active

### ISSUE THREAD

**Issue by velociraptorFood** [roxaskeyheart/Chromatics#23]
When I launch ffxiv Chromatics gets stuck on "Main Menu is still active" and my razer blackwidow chroma just continuously displays the rainbow wave even when I am logged in.

**Comment by logicallysynced** [comment]
Are you running DX11 or DX9?

**Comment by velociraptorFood** [comment]
DX9

**Comment by logicallysynced** [comment]
I see the issue, fixing now.

**Comment by logicallysynced** [comment]
Okay this should be resolved. If you restart Chromatics you should be prompted to update.

Alternatively I have updated the Github releases section with the patched update.

Also just check that the Razer devices are enabled under device tab after the update has completed.

**Comment by velociraptorFood** [comment]
It seems to be working properly now, thanks for the quick fix!
