### ISSUE TITLE
"Start may not be called on a task that has completed."

### ISSUE THREAD

**Issue by Roglef** [roxaskeyheart/Chromatics#25]
Howdy. I love the concept. This seems like it can be amazing. When trying to launch (in Dx9), window was first showing that I was still in main menu, as a previous user had stated recently (https://github.com/roxaskeyheart/Chromatics/issues/23). I had the app check for updates to see if that can be fixed, and it looks like it is the most updated version of the app. 

Upon restarting the app, it was showing that "Watchdog has started," but the keyboard kept flashing as if i were in the main menu, and upon entering a raid, a message showed up "Start may not be called on a task that has completed" while the keyboard continued this.  

I am using a Razer Deathstalker Chroma, so I am not sure if that is related, as I did see that this model is in the "Device is supported, but has limited functionality" category on your site. 

Thanks for the help!

**Comment by logicallysynced** [comment]
The Razer SDK has a bug in it currently which prevents DeathStalker Chroma from working correctly. Waiting for an SDK update to resolve it.

**Comment by logicallysynced** [comment]
This has been resolved in the latest version.

https://github.com/roxaskeyheart/Chromatics/releases
