### ISSUE TITLE
AZERTY

### ISSUE THREAD

**Issue by kaeh** [roxaskeyheart/Chromatics#26]
Hi !

I've just discovered this awesome tool that is Chromatics, but i struggle with the fact it seems to be locked to QWERTY keyboard.

Tell me if i'm wrong or if there is a way to bind the colors on AZERTY instead of QWERTY, but i kinda check the files in [Chromatics_install_path] and found nothing interesting.

**Comment by logicallysynced** [comment]
Planned for 2.2.5
