### ISSUE TITLE
"Main Menu is still active" but it isn't!

### ISSUE THREAD

**Issue by Faeneth** [roxaskeyheart/Chromatics#27]
Hiya! I'm using a Razer Black Widow X, and I get a very nice rainbow when I open FFXIV, during the main menu and my character selection.  Unfortunately, even after choosing my world/character, the flashy rainbows won't go away! In the Chromatics debug log, it just spams "Main Menu is still active".  I've tried restarting both the game, and Chromatics.  Am I doing something wrong?

**Comment by kaeh** [comment]
Hi, i've the same issue sometimes, but on a Razer Chroma.

I just let the game run and restart chromatics, an everything come back to normal.

**Comment by logicallysynced** [comment]
Can you post your debug window outputs here so I could take a peak please?
Also please make sure you are running Chromatics as administrator.

**Comment by logicallysynced** [comment]
Please try the latest release (2.2.3)

https://github.com/roxaskeyheart/Chromatics/releases
