### ISSUE TITLE
Chromatics light effects freeze after one cast.

### ISSUE THREAD

**Issue by Critiko** [roxaskeyheart/Chromatics#28]
Logs show the following upon freezing:
(RightMenu): Object reference not set to an instance of an object.
(Macro1): Object reference not set to an instance of an object.
(Macro2): Object reference not set to an instance of an object.
(Macro3): Object reference not set to an instance of an object.
(Macro4): Object reference not set to an instance of an object.
(Macro5): Object reference not set to an instance of an object.

Keyboard: Corsair RGB Strafe

**Comment by logicallysynced** [comment]
Could you post the entire log to here if possible?

Also if you unplug your keyboard and run the Corsair Keyboard simulator (found in CUE2 settings) what happens?

**Comment by Hercubla** [comment]
I'm also getting this issue.

**Comment by Critiko** [comment]
Starting Chromatics Version 2.1.1 (Beta)
Searching for devices.chromatics..
Attempting to load devices.chromatics..
devices.chromatics loaded.
Searching for settings.chromatics..
Attempting to load settings.chromatics..
settings.chromatics loaded.
Searching for mappings.chromatics..
Attempting to load mappings.chromatics..
mappings.chromatics loaded.
Architecture: x64
The Razer SDK (RzChromaSDK64.dll) Could not be found on this computer. Please install Synapse and restart ACT if you wish to use Chromatics with Razer devices.
Attempting to load CUE SDK..
CUE SDK Loaded (2.4.67/2.13.80)
Attempting to load Logitech SDK..
Logitech SDK failed to load.
Attempting to load LIFX SDK..
LIFX SDK Loaded
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Attempting Attach..
DX9 Initiated
Attached to FFXIV
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Main Menu is still active.
Game Running ()
Watchdog Started
Sequence contains no elements
(RightMenu): Object reference not set to an instance of an object.
(Macro1): Object reference not set to an instance of an object.
(Macro2): Object reference not set to an instance of an object.
(Macro3): Object reference not set to an instance of an object.
(Macro4): Object reference not set to an instance of an object.
(Macro5): Object reference not set to an instance of an object.

**Comment by Critiko** [comment]
I've been having issue with my Strafe, flickering keys, so took a while to RMA but the new one also has flickering keys so been busy with Corsair support...
