### ISSUE TITLE
chromatics 2.1.1 just waving rainbow?

### ISSUE THREAD

**Issue by auserfromff14** [roxaskeyheart/Chromatics#30]
i just download it. and staru using but first it was blue then automaticly change into rainbow wave in every area. so ... help???

**Comment by logicallysynced** [comment]
Please post a screenshot of the debug window, which can be opened from the Chromatics icon in the taskbar.

Additionally are you running DX9 or DX11?

**Comment by auserfromff14** [comment]
im playing it on dx9 [](url) 
![desktop 06 14 2017 - 14 22 24 01](https://user-images.githubusercontent.com/29418418/27120278-20e48204-510d-11e7-898c-af183ee505ae.png)

**Comment by raziell74** [comment]
I am having this same issue

**Comment by reave** [comment]
Same issue.

**Comment by logicallysynced** [comment]
I will look into this after the 4.x compatibility patch.

**Comment by logicallysynced** [comment]
DX11 and Stormblood support has now been added. Please refer to the release section or update from within Chromatics.

https://github.com/roxaskeyheart/Chromatics/releases

Please note that Chromatics is still in beta and bugs may appear.

**Comment by raziell74** [comment]
the new release fixed the problem for me, can the others confirm?
