### ISSUE TITLE
Arx Control Data not accurate

### ISSUE THREAD

**Issue by reave** [roxaskeyheart/Chromatics#31]
Using 2.1.1 Beta, ARX enabled, ACT Web Server URL matching my ACT Web server. I can see the web calls being made, but the HUD, and Party List data is incorrect. The HUD shows Limsa Lominsa constantly. The minimap doesn't display anything and ACT just calls a missing page. 

Here is a screenshot of the Web Server Window in ACT:
![advanced combat tracker_2017-06-14_21-58-55](https://user-images.githubusercontent.com/1323535/27162018-e1ff9d4a-514c-11e7-8cd7-29b70a2ad93a.png)

Here is a screenshot of the Chromatics Window. 
![chromatics_2017-06-14_22-01-41](https://user-images.githubusercontent.com/1323535/27162078-23f41afa-514d-11e7-8681-7dfc527d4acf.png)

I also have the output of my debug window here: https://pastebin.com/mZ2QUCMH

**Comment by logicallysynced** [comment]
ACT integration is still under development. I'm sorry for the inconvenience, I will be looking into this after patching for 4.0
