### ISSUE TITLE
Not working/detecting my device on DX 11? 

### ISSUE THREAD

**Issue by zarry** [roxaskeyheart/Chromatics#34]
Hey, I am currently trying the new beta release that supports DX 11.  It is able to detect my razer sdk, able to detect the game and my character but it does not appear to have any effect.  Did I miss a step in configuration? I attempted running Chromatics as both administrator and normal.  I used the installer version.

I don't see my keyboard listed under devices. Here is output from the debug console.  I removed a chunk of the main menu is still up lines as I can't imagine they are relevant. 

Starting Chromatics Version 2.2.1 (Beta)
Searching for devices.chromatics..
Attempting to load devices.chromatics..
devices.chromatics loaded.
Searching for settings.chromatics..
Attempting to load settings.chromatics..
settings.chromatics loaded.
Searching for mappings.chromatics..
Attempting to load mappings.chromatics..
mappings.chromatics loaded.
Architecture: x64
Razer SDK Detected: C:\Program Files\Razer Chroma SDK\bin\RzChromaSDK64.dll
Razer SDK not found
Attempting to load CUE SDK..
CUE SDK failed to load. EX: Error in the application.
Attempting to load Logitech SDK..
Logitech SDK failed to load.
Attempting to load LIFX SDK..
LIFX SDK Loaded
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
Waiting for Game Launch..
DX11 Initiated
Attached to FFXIV
Main Menu is still active.
Main Menu is still active.
...
Main Menu is still active.
Game Running (Sir Zarry)
Watchdog Started
Watchdog Stopped
Game stopped
Waiting for Game Launch..

**Comment by logicallysynced** [comment]
Are you running the latest version of Razer Synapse?

**Comment by zarry** [comment]
@roxaskeyheart Yessir.  Just upgraded as I hadn't been.  Same issue.  It just says watchdog started and nothing follows.

**Comment by zarry** [comment]
@roxaskeyheart Forgot to add, it does detect my device now.  I actually see a bunch of devices I don't have in the list.  Like headset, etc... But still no change in keyboard.  

Oddly when I tested this on DX 9 back in april it worked fine.

**Comment by zarry** [comment]
@roxaskeyheart only new message that appeared in debug console after doing a battle is below

`
Razer Keyboard (F1): Call to native Chroma SDK function DeleteEffect failed with error: Unknown: Unknown. (1168)
`

**Comment by logicallysynced** [comment]
Please try the latest release (2.2.3)

https://github.com/roxaskeyheart/Chromatics/releases

**Comment by zarry** [comment]
@roxaskeyheart Thank you! This new release resolved my issues.
