### ISSUE TITLE
Razer Chroma V2 SDK Failure

### ISSUE THREAD

**Issue by raziell74** [roxaskeyheart/Chromatics#36]
Running the latest release with DX11 and Stormblood expansion I'm getting errors for the Chroma SDK.

Here is a screenshot of the debug tab.
![Chroma SDK Error](http://imageshack.com/a/img923/2749/iOFDMD.png)

**Comment by logicallysynced** [comment]
Are you running the latest version of Razer Synapse and running Chromatics as administrator?

**Comment by raziell74** [comment]
I did need to update Synapse. Played a quick dungeon with everything fully up to date and came out with another SDK failure. 

`Razer Keyboard (D): Call to native Chroma SDK function DeleteEffect failed with error: RzInvalidParameter: Invalid parameter. (87)
Watchdog Triggered`

Chromatics is also non-responsive.

**Comment by logicallysynced** [comment]
Will have to investigate further.

**Comment by logicallysynced** [comment]
Please try the latest release (2.2.3)

https://github.com/roxaskeyheart/Chromatics/releases

**Comment by raziell74** [comment]
I am happy to report the 2.2.3 release has resolved all issues. Runs like a dream. Thank you for your hard work!

**Comment by logicallysynced** [comment]
Most excellent! Glad to hear it ^^
