### ISSUE TITLE
Chromatics 2.2.4 Beta crashes Logitech Gaming Software.

### ISSUE THREAD

**Issue by ghost** [roxaskeyheart/Chromatics#40]
Whenever I attempt to run Chromatics 2.2.4, LGS will hang and eventually crash.  The crash happens when I open Chromatics 2.2.4 after opening LGS, and will also crash when I open try to access the Chromatics applet through ARX on my phone after opening LGS while Chromatics is already open.  It also fills my applets menu with a lot of garbage data pointing to various .js and .png files [(pictured here)](http://imgur.com/a/yKaJd).  Chromatics itself has no issue connecting with FFXIV itself.

**Comment by logicallysynced** [comment]
This is interesting, what version of LGS are you running? Can you send me a screenshot of the Chromatics directory please?

Additionally did you use the Installer or Portable version?

**Comment by ghost** [comment]
Currently using LGS 8.94, and I installed it using the installer executable.  I tried to download the portable version, but the link just redirected to a 404 page. [This is everything currently inside my x86/Chromatics folder](http://imgur.com/a/FzIpv)
