### ISSUE TITLE
Logitech keyboard backlight updating infrequently

### ISSUE THREAD

**Issue by MrBlackCreep** [roxaskeyheart/Chromatics#41]
After starting chromatics and FFXIV the backlight of my G910 changes accordingly.
Then to test it out I entered combat to lose some health and TP or cast some spells.
To my surprise the backlighting didn't change. It only updates as long as I have the chromatics window in focus and sometimes randomly during combat. There is no kind of error displayed in the log.

**Comment by logicallysynced** [comment]
Did you disable native ffxiv_dx11 led illumination in the LGS software?

Can you post the Chromatics console here for us as well?

**Comment by MrBlackCreep** [comment]
Yes native led illumination for FXIV is disabled and here is the console: https://pastebin.com/tiQmcJE9
After some testing it turns out that the backlighting ONLY updates if FFXIV is not in focus.
Casting, HP, TP etc. updates in real-time as long as the FFXIV window is out of focus. As soon as I switch to it the backlighting freezes in its current state until I switch out again.

**Comment by logicallysynced** [comment]
I can see what you are referring to and this is indeed a bug. Will aim to patch it asap.

**Comment by logicallysynced** [comment]
Please try Version 2.2.5 and see if this resolves your problem. Check out the new Logitech Conflict Control feature in particular.

https://github.com/roxaskeyheart/Chromatics/releases

**Comment by MrBlackCreep** [comment]
Yep, the problem has been resolved.
Though now I'm getting the occasional flicker (roughly every 1-2 minutes) of the keyboard reverting to my standard backlighting set in the Logitech gaming software for half a second or so. Mostly when finishing a cast or switching areas.

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by logicallysynced** [comment]
@danielrouleau Do you know what might be causing that?

**Comment by danielrouleau** [comment]
It may have to do with saving and restoring key colors before/after effects cycle, I'll look into reproducing that. I may not have noticed it yet because my backlight color in LGS is the same as Chromatics.
