### ISSUE TITLE
Unable to uninstall / Check for Updates Issue

### ISSUE THREAD

**Issue by mnemyx** [roxaskeyheart/Chromatics#42]
I was trying to uninstall so I could install the 2.2.4 version to report a different bug about the "Check for Updates". I know 2.2.5 installed over 2.2.4 fine which is why my Logitech devices are recognized now...but eventually, being able to uninstall is nice...Also, I'm not seeing an uninstaller executable in the program files folder.

![2017-07-09_12-46-59](https://user-images.githubusercontent.com/770706/27997057-cfd7670e-64a4-11e7-820b-bb28adc3f64d.png)

In regards to the check for updates - it prompted if I wanted to update just fine, but the pop-up afterwards had an error somewhere along the lines of, "Could not find specified file..." 

These are just QoL stuff, but I figured I'd flag it for you guys in case.

Thank you for all you guys work!

**Comment by logicallysynced** [comment]
Yes an uninstaller is a good idea, in the mean time deleting the folder will do the job as well. 👍

**Comment by mnemyx** [comment]
Ohhh, good to know. I guess it's small enough to not require any hassle with the registry and stuff. I just never know what a program on windows ends up doing.

(Im a Linux-based developer; Idk how you guys handle Windows >_>; Godspeed.)

**Comment by logicallysynced** [comment]
Added an uninstaller to 2.2.6.
