### ISSUE TITLE
[Feature Request] Add LimitlessLED/Milight LED Lightbulb support

### ISSUE THREAD

**Issue by denali1** [roxaskeyheart/Chromatics#44]
Dev information can be found at http://www.limitlessled.com/dev/.

**Comment by logicallysynced** [comment]
I will look into this for 2.2.7 or 2.2.8, however I don't have one of these devices to test and from looking at the SDK, I don't believe I will be able to program this for individual bulbs - it will be all bulbs on a hub most likely.
