### ISSUE TITLE
Chromatics failing to load Razer SDK despite detecting it. 

### ISSUE THREAD

**Issue by Nainlx1** [roxaskeyheart/Chromatics#45]
As the title says the program can't load my Razer SDK despite detecting it. 

Starting Chromatics Version 2.2.6 (Beta)
Attempting to load LIFX SDK..
LIFX SDK Loaded
Searching for devices.chromatics..
Attempting to load devices.chromatics..
devices.chromatics loaded.
Searching for settings.chromatics..
Attempting to load settings.chromatics..
settings.chromatics loaded.
Searching for mappings.chromatics..
Attempting to load mappings.chromatics..
mappings.chromatics loaded.
Attempting to load Razer SDK..
Architecture: x64
Razer SDK Detected: C:\Program Files\Razer Chroma SDK\bin\RzChromaSDK64.dll
Razer SDK not found
Razer SDK failed to load.
Attempting to load Logitech SDK..
Logitech SDK failed to load.
Attempting to load CUE SDK..
CUE SDK failed to load. EX: Value cannot be null.
Parameter name: ptr
CUE SDK failed to load.
Attempting Attach..
DX11 Initiated
Attached to FFXIV
Game Running (Yektai Khatayin)
Watchdog Started

Here is the debug log. I have Chromatics 2.2.6 and Razor Synapse is on verison 2.20.

**Comment by logicallysynced** [comment]
Is Razer Synapse up to date and Chroma Apps turned on in its settings?

**Comment by Nainlx1** [comment]
Yes it is both up to date and Chroma Apps are on. Other Chroma apps like visualizer and Game dog are working just fine

**Comment by logicallysynced** [comment]
Are you using the portable or installer version of Chromatics?

**Comment by Nainlx1** [comment]
I figured it out. I uninstalled Synapse and the SDK and redownloaded them from razer's website and now it's working just fine.
