### ISSUE TITLE
Casting Effect Not Working Right On Corsair K95

### ISSUE THREAD

**Issue by KnightSatellite** [roxaskeyheart/Chromatics#46]
After the casting effect was moved to the F keys only keys F7/F8/F9/F11/F12 light up. This is on a Corsair K95 rgb

**Comment by logicallysynced** [comment]
Interesting, I'll have to look into this. Thanks for bringing it to my attention.

If you open up the K95 emulator in the CUE2 software (uncheck show only connected devices), does it do the same thing?

**Comment by KnightSatellite** [comment]
Yes it does the same, I made a gif using the emulator to show what is happening http://i.imgur.com/j791u9i.gif sometimes the F10 key for the TP bar will stay turned off if tp is at 0 when you start Chromatics and will not light up at all when casting, same with the F12 key.

**Comment by logicallysynced** [comment]
This should hopefully be fixed in 2.2.9 but I can't check on a physical device.
