### ISSUE TITLE
Error in 2.2.8

### ISSUE THREAD

**Issue by Itay-david-davidson** [roxaskeyheart/Chromatics#49]
I can't get version 2.2.8 to work, previous version worked wonderfully however this one keeps giving me errors in both protable and installer version, different error for each. Also after pressing X on the window, the program is still in the tray bar but cannot be opened again.
In the install version it says something about corsairlib.setlights (color col), about GlobalApplyAllKeyLightning, and about ProcessFFxivData.
 I cannot copy and paste the error messages and they keep updating every sec so I can't really write it out that much.

**Comment by logicallysynced** [comment]
This is a known bug and I'm working to resolve it asap.

In the mean time, a work around you can do use is to enable Advance mode and turn on the device emulators in the CUE2 software. This fixes the problem temporarily.

**Comment by TJNaish** [comment]
Yup, that seems to have done the trick!

Silly corsair software...

Thanks! =D

**Comment by logicallysynced** [comment]
No worries.

I have fixed this in 2.2.9 also.
