### ISSUE TITLE
Parse Error (2.2.8)

### ISSUE THREAD

**Issue by TJNaish** [roxaskeyheart/Chromatics#50]
Hey, I just found this and thought I'd give it a go.

I have a Logitech g910. I can get the Arx controller working (shows my HUD info and in game time etc), but i keep getting a prase error and the lighting effects don't seem to work at all.

![image](https://user-images.githubusercontent.com/31592212/30003949-049ff60a-90be-11e7-8fa1-6be05b99c1cb.png)

**Comment by logicallysynced** [comment]
This is fixed in 2.2.9 but I'm still working on a few things before I can release it.

Do you have Corsair's CUE2 software installed on your computer by any chance?

**Comment by TJNaish** [comment]
Yeah, I have actually!

I have it for a Corsair VOID headset, just tried running Chromatics and XIV again after closing CUE and it's happy with that it seems!

**Comment by logicallysynced** [comment]
Okay so what you need to do, is go into CUE2 settings and **uncheck** the box that says "Show Only Connected Devices". That should be a temporary work around.

**Comment by logicallysynced** [comment]
Fixed in 2.2.9
