### ISSUE TITLE
Keybind colours don't work

### ISSUE THREAD

**Issue by Itay-david-davidson** [roxaskeyheart/Chromatics#51]
Hi. It seems that in both 2.2.8 and 2.2.9 the keybind colours don't work. When it's out of range the colour doesn't change, nor when it on cd nor when it proc'd.
I keep using the 2.2.7 version where it does seem to work.

Also having a better control on where each thing is represented on the keyboard (enmity, duty finder bell, etc) or just being able to see it without guessing would be nice sometime in the future.

**Comment by logicallysynced** [comment]
The keybind values seem to be working for myself as well as other users so it's hard to say why they may not be working for you. There is also no difference between 2.2.7 and 2.2.8/2.2.9 in terms of the programming that drives those features so it's a bit confusing.

Please try deleting the Chromatics cache files by first fully exiting Chromatics, then going into the Chromatics directory and deleting all the **.json** and **.chromatics** files you can see. Then reload Chromatics again and see if this resolves the issue. 

In addition, please make sure the **enable keybind effects** option is **checked** and the **use local cache** is **unchecked** under the settings tab.

**Comment by Itay-david-davidson** [comment]
Seems disabling and re-enabling it did the trick. Thanks!
