### ISSUE TITLE
Huton gauge blinking

### ISSUE THREAD

**Issue by Itay-david-davidson** [roxaskeyheart/Chromatics#52]
When Huton is either Full (or very close to) or Empty (or, again very close to be) the Huton part of the keyboard starts blinking like crazy. While it is useful to show when you're about to run out, it's annoying when it keeps going long after it ran out, you exited combat and even changed to a different class. And there's no reason for it to blink while full.

**Comment by logicallysynced** [comment]
I believe this is now fixed in the latest commit, however I have no way of testing as I don't have a NIN levelled. You can download the build from here:

https://chromaticsffxiv.com/chromatics2/Chromatics2.2.9BETA-Installer.exe

**Comment by Itay-david-davidson** [comment]
It still blinks when full and IMO starts blinking too early (12 sec before it runs out). But except that it works well.

Edit: Also sometimes after it ran out, it shows as full.
