### ISSUE TITLE
LCD displays "Mana" where it should display "Latency"

### ISSUE THREAD

**Issue by fixel99** [roxaskeyheart/Chromatics#53]
Just a small thing but thought I should mention it. (Don't know why picture is sideways :P)
![20170911_185151](https://user-images.githubusercontent.com/11691966/30266513-eec63450-9722-11e7-9062-ef5191f00977.jpg)

Edit: Am sometimes able to access this screen as well, but it never changes from 0
![20170911_185828](https://user-images.githubusercontent.com/11691966/30266682-83ceb428-9723-11e7-88be-ed44d57f768e.jpg)

**Comment by logicallysynced** [comment]
The latency text changes to show the name of the Datacenter currently selected. Mana being on of the Japanese servers if I recall.

You should be able to use the up and down controls to find your Datacenter.

**Comment by fixel99** [comment]
Oh oops my mistake!
