### ISSUE TITLE
Not necessarily an issue, but a request?

### ISSUE THREAD

**Issue by khyberelessidil** [roxaskeyheart/Chromatics#57]
I'm having a bit of difficulty remembering which areas are designated to which functions on my Razer Chroma keyboard...  Maybe add a section to list which functions are bound to which keys/areas?  Would help recoloring a LOT, and make it easier to identify "stuck" areas (areas that aren't responding).  I've had intermittent areas just....stop working until I relaunched, but sometimes it's tricky to tell which module it is because of overlap and/or similar colors.  Thanks for your time, and LOVE the project!!!

**Comment by logicallysynced** [comment]
https://github.com/roxaskeyheart/Chromatics/wiki
