### ISSUE TITLE
Working for one Day

### ISSUE THREAD

**Issue by Quentech** [roxaskeyheart/Chromatics#58]
Hello i had a problem. One Day the all was fine, on the next day dosent work it. 
I checkt the Config
by the way i use Windows 10 and a Logitech G910
G Software no Persist and the controll of the games is allowed. Chromatics is Conflict Control and auto enable/disable is on. 
Discord and FF are all disable Chromatics isa Backlight and Arx enable
i start Chromatics as Admin than FF normal (i test Admin also) only the 1,2,3,4 key have light. If FF start the Profile of the logitech switch to default game Start. if i minimaize the window the debug log dosent show an error. i click on the window of chromatics and ff go to fullscreen but only The 1,2,3,4 key light up. Arx is work.
What can i do ?
Ohhh clear Cache i use many times.
Please help

**Comment by logicallysynced** [comment]
It’s a good idea to always start and be logged into FFXIV before running Chromatics.

I would try completely uninstalling and reinstalling Chromatics if you’re having these sorts of issues, also consider reinstalling LGS if it persists.

**Comment by Quentech** [comment]
Ok now it works fine. Was an Option in the lsg allow overwolf to control the Backlight Thx

**Comment by Quentech** [comment]
Starting Pc, starting ff, starting Chromatics. but dosent work :(
thx for help
