### ISSUE TITLE
Bug/Request - Razer Naga Hex v2

### ISSUE THREAD

**Issue by RudiAk** [roxaskeyheart/Chromatics#59]
Hi,
Wondering if you could have a look at this;The lights around the thumb keys (7 buttons) do not light up. none of the settings available are linked to this.

Thank You

**Comment by Paladinleeds** [comment]
In 2.3.9 they fixed it for the Naga Trinity such that the numpad (7-key or 12-key) appears under lighting zone 3 (to be clear, this is zone and not strip). It might be that this is now fixed for you as well. Is worth looking at.
