### ISSUE TITLE
Logitech Troubleshooting

### ISSUE THREAD

**Issue by warforged44** [roxaskeyheart/Chromatics#60]
According to the logs in the debug tab, everything should be working just fine, but I am not seeing any color changes on my Logitech G910 when I start or enter the game.
Attempting to follow the instructions in the Logitech: Read First section, I discovered that there is no LCD Control option that I can check.
https://imgur.com/a/7PH2B
I'm not certain how I can proceed so I can see how this plugin will actually work for my keyboard. Please advise.

**Comment by warforged44** [comment]
I'm using a Logitech G910 Orion Spectrum. 
I'm running Chromatics as Admin.
In the Logitech Gaming Software, ffxiv_dx11 LED Backlighting is disabled.
Chromatics is enabled in LGS, though as mentioned, I only have a checkbox for Arx Control.

Here's my Chromatics Debug log:
Starting Chromatics Version 2.3.1 (Beta)
Searching for devices.chromatics..
Attempting to load devices.chromatics..
devices.chromatics loaded.
Searching for settings.chromatics..
Attempting to load settings.chromatics..
settings.chromatics loaded.
Searching for mappings.chromatics..
Attempting to load mappings.chromatics..
mappings.chromatics loaded.
Attempting to load Razer SDK..
The Razer SDK (RzChromaSDK64.dll) Could not be found on this computer. Uninstall any previous versions of Razer SDK & Synapse and then reinstall Razer Synapse.
Razer SDK failed to load.
Attempting to load Logitech SDK..
Logitech SDK Loaded
Attempting to load CUE SDK..
CUE SDK failed to load. EX: Error in the application.
CUE SDK failed to load.
Attempting to load Coolermaster SDK..
Unable to find any valid Coolermaster devices.
Coolermaster SDK failed to load.
Attempting to load LIFX SDK..
LIFX SDK Loaded
Logitech Conflict Mode is already enabled.
Game Language set to English.
No new updates currently available.
Waiting for Game Launch..
Attempting Attach..
DX11 Initiated
Attached to FFXIV
Main Menu is still active.
Game Running (Keogan Stoneleader)

**Comment by danielrouleau** [comment]
Did you run the installer or the portable zip for Chromatics? I think the fact that it doesn't show LED Backlighting for Chromatics in Logitech Gaming Studio may be the problem since mine does show that, though I'm not sure why it doesn't show up. I just rebuilt my computer and using the 910 with Chromatics is working for me, but I also see that option that you do not see. For what it is worth, I am using the portable zip file with success, running as Administrator.

**Comment by logicallysynced** [comment]
Also try reinstalling LGS if you haven’t already, it’s can be quite an annoying application to deal with sometimes it seems

**Comment by warforged44** [comment]
I used the installer for Chromatics. I’ll try reinstalling Chromatics from the ZIP and reinstalling LGS and report back.

**Comment by warforged44** [comment]
Mission success. I was able to choose the LED Backlighting that was previously unavailable to me, now it all seems to work just fine. My only complaint at this time is that my tenkey area isn't showing the cooldowns for the abilities I have bound there. My job gauge seems to interfere with that area, perhaps, as only the minus, plus, and enter keys there are colored.

**Comment by R3537L1F3** [comment]
I have this issue. Reinstalling LGS and using the ZIP version apeared to work (but broke my ARX app) after restarting the computer however, the ARX app is functioning again but now the LED Backlight option has vanished again. Any ideas?
