### ISSUE TITLE
Run on Windows Start

### ISSUE THREAD

**Issue by Bob1361** [roxaskeyheart/Chromatics#61]
Hello,

I wish you a very happy new year 2018!

I use your program since the acquisition of my new Corsair keyboard.
I really love the color scheme and the animations, it's really a crazy job you've done! Bravo!

Nevertheless, i encounter a bug on the "Settings" tab.
I check the box "Run on Windows Start" it does not remain active when restarting my computer ...
Systematically i have to restart it on each start of FFXIV.

![image](https://user-images.githubusercontent.com/35082681/34543704-9d404264-f0e2-11e7-916d-3074c031a68e.png)

Do you have any idea?

Congratulations for your work and see you soon!

Bob Littleleg - Ragnarok

**Comment by logicallysynced** [comment]
Are you running Chromatics as administrator? That plays an important role in allowing the game to run on system start.

**Comment by ccheveaux** [comment]
Yes, since the beginning :)

![image](https://user-images.githubusercontent.com/22099903/35483212-d13cc36a-043f-11e8-9e52-ffa7c27af254.png)

**Comment by ccheveaux** [comment]
Hi and thx for this update of Chromatics 👍 
The problem of automatic start is still present on this new version.

And yet I checked again and the software starts well with administrator rights.
I could do it manually on Windows 10 but I find it a pity that the software that incorporates the functionality can not do it itself.

Moreover, when Final Fantasy is not launched or a character is not attached I see that the keyboard displays a color template that I had not set on the original software.
Would there be a place in Chromatics where I can search for a default template for use off Final Fantasy attached?

Thank you !

PS: I see you looking for help, a developer in C?
Being computer scientist I would like to help you but I do not know at all this computer language ...

**Comment by Bob1361** [comment]
Hi and thx for this update of Chromatics 👍 

I have two account : Bob1361 and ccheveaux.
Bob1361 is personnal and ccheveaux is for my job.
I mistakenly posted with my professional account the last time.

The problem of automatic start is still present on this new version.

And yet I checked again and the software starts well with administrator rights.
I could do it manually on Windows 10 but I find it a pity that the software that incorporates the functionality can not do it itself.

Moreover, when Final Fantasy is not launched or a character is not attached I see that the keyboard displays a color template that I had not set on the original software.
Would there be a place in Chromatics where I can search for a default template for use off Final Fantasy attached?

Thank you !

PS: I see you looking for help, a developer in C?
Being computer scientist I would like to help you but I do not know at all this computer language ...

**Comment by logicallysynced** [comment]
So Chromatics writes to your registry to make it a startup program, in particular this entry here:

HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run

Can you see the Chromatics entry here?

I will try and make the "default" colour just a wash of the base colour for now.

**Comment by Bob1361** [comment]
For "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" i have this : 

![image](https://user-images.githubusercontent.com/35082681/36352635-3a7d44bc-14bc-11e8-9f7e-9b196f906b77.png)

I don't understand why Chromatics doesn't start with Windows ...

**Comment by logicallysynced** [comment]
By any chance are you using the Start Screen instead of the usual Windows Start Menu?

**Comment by Bob1361** [comment]
I use Cortana in search bar to start Chromatics.
I have a shortcut in my bar too.

![image](https://user-images.githubusercontent.com/35082681/36353193-9e28158a-14c3-11e8-8649-37e3a1c86d43.png)

**Comment by logicallysynced** [comment]
Hmm this sounds like it is a Windows issue somewhere, but I'm really not sure what exactly it could be.. :/

**Comment by Bob1361** [comment]
Maybe it has nothing to do but I have a SmartScreen notification every time I try to install.
I tried to disable it but Chromatics still does not start with Windows.

Another point that I have not mentioned, if I check the automatic start box and I left Chromatics.
The information in the registry as well as the programs starting automatically (in the task manager (start tab) are present.
But if I restart Chromatics manually the box is unchecked while the information (registry and programs started at startup) are still present.

![image](https://user-images.githubusercontent.com/35082681/36374424-9555599c-156b-11e8-8313-194193f9fa55.png)

I would be curious to know in which file it finds the information which records in the registry this automatic start.
I feel that the action is not entirely done.
