### ISSUE TITLE
Razer Cynosa Stuck in Wave Mode

### ISSUE THREAD

**Issue by Teacle** [roxaskeyheart/Chromatics#62]
I launched the game, and then launched the Chromatic app, which worked lovely by the way, might want to add Cynosa by Razer to your compatibility list. However after closing the game and the app, my keyboard is now in Wave mode, causing the lights to fluctuate from left to right. This is odd seeing as how I have an advanced chroma selected and wave is nowhere in it. It's not even selected as my basic chroma. Nothing I do will change the keyboard from the wave pattern, it appears to be stuck. I thought I would make a bug report before restarting or unplugging the keyboard, because it still happened, and therefore, is still a bug.

**Comment by logicallysynced** [comment]
As a temporary work around you could try exiting Chromatics first before quitting FFXIV.

I’ll look into this bug however in the future.

**Comment by spider623** [comment]
i have the same bug on my blackwidow x chroma, looks like it's a general sdk bug
