### ISSUE TITLE
Parser error

### ISSUE THREAD

**Issue by khyberelessidil** [roxaskeyheart/Chromatics#65]
Parser B: Object reference not set to an instance of an object.

There WAS just an update to FFXIV, so I'm guessing that's probably related.  However, I wanted to officially 
bring it to attention just in case!

The app itself loads fine, attaches to the game even, but can't seem to capture character information, just sets the Chroma function back to rainbow mode.

**Comment by logicallysynced** [comment]
Yush this is related to FFXIV 4.2 release. We will release an update in the next week or so to fix compatibility.
