### ISSUE TITLE
German keyboard layout ß doesn't light up as expected

### ISSUE THREAD

**Issue by danielrouleau** [roxaskeyheart/Chromatics#66]
Reported by user in Discord, key shows up as 'ß' in keybind but doesn't light up properly, this is likely similar to https://github.com/antonpup/Aurora/issues/123 and associated fix https://github.com/antonpup/Aurora/commit/4a9082f4fdfda1d26f26270ad322c605e64bec96 where different settings are needed for different regional keyboard settings.
Keyboard: Corsair K95 RGB Platinum

**Comment by logicallysynced** [comment]
I've added a new selector in the GUI for changing the keyboard region in https://github.com/roxaskeyheart/Chromatics/commit/ba41bb5a7b9fb15198e3843463f9d6e5bef21278

And removed the old checkbox.

The tricky part is seeing how each library deals with international keys, especially when we cant emulate them. https://github.com/DarthAffe/CUE.NET/blob/master/Devices/Generic/Enums/CorsairLedId.cs

**Comment by logicallysynced** [comment]
Added a new framework to make localising keys easier.

https://github.com/roxaskeyheart/Chromatics/commit/67db9e983c678adab32f1e83ff433ebfdca2a22f

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
