### ISSUE TITLE
Lighting not changing on my devices.

### ISSUE THREAD

**Issue by ryangjpriorx** [roxaskeyheart/Chromatics#71]
> Starting Chromatics Version 2.3.6 (Beta)
> Searching for devices.chromatics..
> Attempting to load devices.chromatics..
> devices.chromatics loaded.
> Searching for settings.chromatics..
> Attempting to load settings.chromatics..
> settings.chromatics loaded.
> Searching for mappings.chromatics..
> Attempting to load mappings.chromatics..
> mappings.chromatics loaded.
> Attempting to load Razer SDK..
> Razer SDK Loaded (2.10.0)
> Attempting to load Logitech SDK..
> Logitech SDK failed to load.
> Attempting to load CUE SDK..
> CUE SDK Loaded (2.18.127/2.23.40)
> Attempting to initializer Coolermaster support...
> Did not find any supported Coolermaster devices.
> Coolermaster SDK failed to load.
> Attempting to load LIFX SDK..
> LIFX SDK Loaded
> Game Language set to English.
> No new updates currently available.
> Attempting Attach..
> DX11 Initiated
> Attached to FFXIV
> Main Menu is still active.
> Game Running (Ryan Xero)

as the title suggests chromatics isnt doing anything after launch. Windows 10 and up to date,

**Comment by logicallysynced** [comment]
What device/s are you using?

**Comment by ryangjpriorx** [comment]
I solved it. For future reference the problem for my keyboard was solved by using Razer Synapse 3. However my mouse the Naga chroma can only use legacy Synapse 2. It seems chroma doesn't work on legacy Synapse anymore.
