### ISSUE TITLE
[Feature Request] Eorzea Time based alert

### ISSUE THREAD

**Issue by CraigWoolgar** [roxaskeyheart/Chromatics#72]
As a gatherer I want the keyboard to be able to alert me at a specfic time (as determined within the UI) so that I can be made aware of Unspoiled Spawns.

The vague way I see this working is a new tab in the UI where you can set a single or repeat alarm that will alert with both custom audible alert and visual keyboard alert.

**Comment by logicallysynced** [comment]
This isn't too hard to actually implement so I'll have a look into it.

There is something that already exists that does an audible alert however, but I'm sure you know about it already.

http://www.garlandtools.org/bell/

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
