### ISSUE TITLE
Keyboard highlights not recognising customised modifer keys used

### ISSUE THREAD

**Issue by Paladinleeds** [roxaskeyheart/Chromatics#76]
For example, when you add ALT as a modifier key in order to access hotbar 3 (CTRL accesses bar 2), while keeping the first hotbar on "Bar 1" (so your non-modified abilities), ALT remains the base colour, and does not take on the highlight colour (like how CTRL does)

**Comment by logicallysynced** [comment]
Fixed in 2.3.9
