### ISSUE TITLE
Error on Installation (Corsair k95 RGB)

### ISSUE THREAD

**Issue by Dugthefreshest** [roxaskeyheart/Chromatics#8]
when i try to install through the zip, or through ACT, i get "unable to load DLL' logitechledengineswrapper': the specified module could not be found. (exception from HRESULT: 0x8007007E).  I do not have any logitech devices that would use RGB, just a logitech mouse.

trying to setup a corsair k95 RGB chroma. Great software. Thanks for the support.

Any ideas?﻿

**Comment by logicallysynced** [comment]
This issue is partly a bug I'm looking to fix in an upcoming release.

That being said your problem might be temporarily solved by disabling Logitech Gaming Software before opening Advanced Combat Tracker. The logitechledengineswrapper bug will only trigger if it detects the LGS software running when ACT/Chromatics starts up, therefore by quitting LGS altogether beforehand, it should skip over trying to initialize the Logitech SDK. Once ACT/Chromatics is loaded you should be able to re-open LGS as well.

Also don't forget to run ACT as administrator.

**Comment by Dugthefreshest** [comment]
I was able to install it, but after re opening, it get the message "an attempt was made to load a program with an incorrect format (exception from HRESULT 0x8007000b)

**Comment by logicallysynced** [comment]
Can you please post a screenshot and also list your Operating System, 32-bit/64-bit, etc.

**Comment by Dugthefreshest** [comment]
Thanks for the support, but upon trying it out today, i got it to install, new issue though.

This time it works, I can change the default color for enmity, but, when engaged in battle, the keyboard doesnt change.

**Comment by logicallysynced** [comment]
Does ACT log the battle data?

**Comment by Dugthefreshest** [comment]
![parse](https://cloud.githubusercontent.com/assets/14213491/12603453/cb329388-c480-11e5-888c-95d927b8140a.PNG)

no it was not, this is my latest message.  which happened after i tried to install the FFXIV parser from the wizard.  is there a 64 bit act? would that fix the problem?

**Comment by logicallysynced** [comment]
ACT should run on both 32 and 64 bit machines. That being said Chromatics and FFXIV Parser will only run on 64-bit machines. ACT should by default start 64-bit however you can make sure by opening the 64-bit program in program files.

C > Program Files (x86) > Advanced Combat Tracker > Right-Click **Advanced Combat Tracker.exe** > **Run as Administrator**

![actx64](https://cloud.githubusercontent.com/assets/11515784/12606170/133c65c4-c51b-11e5-9500-cdb47cf5a884.png)

**Comment by Dugthefreshest** [comment]
So After some digging i found a reddit thread with a "solution".  By clicking "Disable Parsing from Network Data" I was able to get it to work just fine.  When I was doing "test connection" it was failing with a windows firewall error, which apparently in 8.1, seems to be an issue?

Besides that, the chat notifications arent working. Mind you, i have a corsair RGB k95 if that is the issue

**Comment by logicallysynced** [comment]
Glad you got it sorted out, though I believe chat notifications require Network parsing to be switched on :/
