### ISSUE TITLE
Failing to load CUE SDK

### ISSUE THREAD

**Issue by DerajMai** [roxaskeyheart/Chromatics#80]
This just started happening yesterday but when I try and use Chromatics (with Razer) it attaches to the game but only some of the lights change on my keyboard and won't change to anything else. Looking at the launcher for Chromatics I have this error:

Starting Chromatics Version 2.3.7 (Beta)
Searching for devices.chromatics..
Attempting to load devices.chromatics..
devices.chromatics loaded.
Searching for settings.chromatics..
Attempting to load settings.chromatics..
settings.chromatics loaded.
Searching for mappings.chromatics..
Attempting to load mappings.chromatics..
mappings.chromatics loaded.
Attempting to load Razer SDK..
Razer SDK Loaded (2.13.2)
Attempting to load Logitech SDK..
Logitech SDK failed to load.
Attempting to load CUE SDK..
CUE SDK failed to load. EX: Error in the application.
CUE SDK failed to load.
Attempting to initializer Coolermaster support...
Did not find any supported Coolermaster devices.
Coolermaster SDK failed to load.
Attempting to load LIFX SDK..
LIFX SDK Loaded
Game Language set to English.
No new updates currently available.
Waiting for Game Launch..

Any ideas?

**Comment by logicallysynced** [comment]
Chromatics hasn’t been updated for 4.3 yet, ETA is currently unknown but you will receive an in-app request to update when one is available.

Sorry for the inconvenience. >.<
