### ISSUE TITLE
Some key doesn't work as expected

### ISSUE THREAD

**Issue by gutthegut** [roxaskeyheart/Chromatics#81]
Just installed Chromatics to test it with my new Razer Blackwidow Chroma V2.

Remaped key work as expected, spells i bind to 'A' 'E' or 'R' worked perfectly. (turn red while i can't use it, yellow for combo and change correctly if i use shift or ctrl)
But none of the key from '&' to '=' change while in CD or Combo.

Don't know if it's linked, but only 'Z' 'S' and 'D' have the highlight color, the 'Q' stay blue.

i'm using an "AZERTY-FRENCH" layout if it can help. 

Already uninstalled synapse 2 to test it with synapse 3, uninstalled chromatics. i also tested chrommatics 2.3.8 and 2.3.7 with no change.

if someone have an idea to fix it, that'll be great. 

(my english's not really great, sorry about that.)

**Comment by logicallysynced** [comment]
Not all the keys currently support keybind highlighting, usually due to the fact they’re used for bother effect (for example job gauges on the NumPad block keybind highlighting on the NumPad). I can’t remember what & and = are used for, but it’s possible the Azerty key layout changes these. I’ll have to look into that.

Also make sure your keyboard mode is set to AZERTY in the devices tab under keyboard.

**Comment by gutthegut** [comment]
when i said "from '&' to '='" i mean all of them. (from 1 (&) to = (+) )

Already set it to azerty. With the qwerty set i have the "wzsd" key highlighted, but with  "azerty" only "zsd" (and not q)


Edit: I just used the qwerty localization from windows, the & to = keys now working as expected. (Don't know what resolved that issue but it worked)

Edit2: still not working as soon as i switch back my keyboard to azerty. Problem is probably there. 

Anyway, the q key still stay blue. Thx for your time. =)

**Comment by gutthegut** [comment]
If it can help you, going to 2.3.3 solve the "zqsd" problem. (but in 2.3.3 the cooldown doesn't work at all)
Problem probably come from the way the keyboard is handled since 2.3.3
i'll try to go into the code myself, if i found something, i'll tell you.

**Comment by gutthegut** [comment]
little update. 
I tweak it, barbarian style. Downloaded the master to check by myself if i can do things. 

i just replaced the key in the FFXIVHotbar.cs file
replaced 

`
//Keys
            {"1", "D1"},
            {"2", "D2"},
            {"3"", "D3"},
            {"4", "D4"},
            {"5", "D5"},
            {"6", "D6"},
            {"7", "D7"},
            {"8", "D8"},
            {"9", "D9"},
            {"0", "D0"},
            {"A", "A"},
            {"B", "B"},
            {"C", "C"},
            {"D", "D"},
            {"E", "E"},
            {"F", "F"},
            {"G", "G"},
            {"H", "H"},
            {"I", "I"},
            {"J", "J"},
            {"K", "K"},
            {"L", "L"},
            {"M", "M"},
            {"N", "N"},
            {"O", "O"},
            {"P", "P"},
            {"Q", "Q"},
            {"R", "R"},
            {"S", "S"},
            {"T", "T"},
            {"U", "U"},
            {"V", "V"},
            {"W", "W"},
            {"X", "X"},
            {"Y", "Y"},
            {"Z", "Z"},
`
by 

`//Keys
            {"&", "D1"},
            {"é", "D2"},
            {"\"", "D3"},
            {"4", "D4"},
            {"(", "D5"},
            {"6", "D6"},
            {"è", "D7"},
            {"_", "D8"},
            {"ç", "D9"},
            {"à", "D0"},
            {"Q", "A"},
            {"B", "B"},
            {"C", "C"},
            {"D", "D"},
            {"E", "E"},
            {"F", "F"},
            {"G", "G"},
            {"H", "H"},
            {"I", "I"},
            {"J", "J"},
            {"K", "K"},
            {"L", "L"},
            {"M", "M"},
            {"N", "N"},
            {"O", "O"},
            {"P", "P"},
            {"A", "Q"},
            {"R", "R"},
            {"S", "S"},
            {"T", "T"},
            {"U", "U"},
            {"V", "V"},
            {"Z", "W"},
            {"X", "X"},
            {"Y", "Y"},
            {"W", "Z"},`

(can't switch 4 to ' and 6 to - while doing \" for 3 worked perfectly. )

And now it works. ( chromatics still run in azerty mode)

If i correctly got what i've done, think the problem comes from final fantasy who in azerty don't return  

> 1 2 3 ... 

 but 

>  & é " ...

**Comment by logicallysynced** [comment]
Thanks, I'll implement this in the next patch. :)
