### ISSUE TITLE
Pet hotbar modifier doesn't adjust lighting

### ISSUE THREAD

**Issue by Paladinleeds** [roxaskeyheart/Chromatics#84]
So, if you have a button for your pet hotbar modifier (in my case, SHIFT), when you hold the pet hotbar modifier (so in my case, holding SHIFT), it does not adjust your number row to showcase the usability of abilities on your pet. It just remains on whatever other modifiers are currently held (if shift is the only modifier being held, it will showcase lights for hotbar 1)..

It should be noted that this adjustment in lighting to the pet hotbar should only take effect is the ONLY modifier being held down is for the pet hotbar. CTRL is modifier 2 for my setup, and holding CTRL + SHIFT (doesn't matter in what order I actuate them) it still uses hotbar 2 in-game for what to cast.

**Comment by logicallysynced** [comment]
See Discord for more information.
