### ISSUE TITLE
Error 500 with 2.4.0

### ISSUE THREAD

**Issue by Bob1361** [roxaskeyheart/Chromatics#85]
Hello,

I update Chromatics in 2.4.0 version today.
Thx again for support ;)

I have an error 500 and my keyboard have not a good color : 

![image](https://user-images.githubusercontent.com/35082681/41612599-ae5ac706-73f3-11e8-82ab-e242a49f478d.png)
![image](https://user-images.githubusercontent.com/35082681/41612613-b84173c8-73f3-11e8-8167-9d743631f831.png)

I disable my firewall and antivirus, but same issue.
This is the complete log.

![image](https://user-images.githubusercontent.com/35082681/41612581-a1407bc4-73f3-11e8-9934-febb14de2615.png)

Do you have an idea ?

Thx :)

**Comment by logicallysynced** [comment]
This is caused by the API site being offline currently. I will contact the site owner and see what’s happening but it might take some time to resolve.

In the mean time, within Chromatics you can try selecting “Use Local Cache” from the settings tab and restarting Chromatics to see if that resolves your issue?

**Comment by Bob1361** [comment]
Wow quick answer thx :)

I try with check "Use Local Cache" but same issue.
I can wait the answer of your site owner ;)

**Comment by logicallysynced** [comment]
You might also need to change the language in Chromatics to English.

**Comment by Bob1361** [comment]
Hmmm same with English and "Clear Cache" button.

But when i uninstall, delete folder "C:\Program Files (x86)\Chromatics" and reinstall Chromatics work.
I stop and run again with no problem.

But if i switch language to French the error 500 is back ;)
So in waiting i stay in English.

**Comment by Bob1361** [comment]
It works again !
Thank you very much ;)

Other question quickly.
I see many new fonctionnality in changelog.
Have you a documentation or screenshot other than the wiki ?

**Comment by logicallysynced** [comment]
We're working on a more official documentation at the moment as well as some videos but it's taking a bit longer than we expected. Feel free to join our Discord if you had any questions though!

https://discord.gg/sK47yFE
