### ISSUE TITLE
Chromatics not lighting up on Razer devices.

### ISSUE THREAD

**Issue by MrCTT** [roxaskeyheart/Chromatics#86]
I've got a Blackwidow Chroma v2, a Razer Deathadder Mouse, and a Razer Firefly. Using chromatics 2.41, and they have not activated to Chromatics at all.
Got a log for you. 

Starting Chromatics Version 2.4.1
Searching for devices.chromatics..
Attempting to load devices.chromatics..
devices.chromatics loaded.
Searching for settings.chromatics..
Attempting to load settings.chromatics..
settings.chromatics loaded.
Searching for mappings.chromatics..
Attempting to load mappings.chromatics..
mappings.chromatics loaded.
Attempting to load Razer SDK..
Razer SDK Loaded (1.0.0.0)
Attempting to load Logitech SDK..
Logitech SDK failed to load. Please make sure LGS is running.
Attempting to load Corsair SDK..
CUE SDK Loaded (2.18.127/2.24.50)
Attempting to initializer Coolermaster support...
Did not find any supported Coolermaster devices.
Coolermaster SDK failed to load.
Attempting to load SteelSeries GameSense SDK..
SteelSeries SDK failed to load. Please make sure SteelSeries Engine is running.
Attempting to load Wooting SDK..
No Wooting devices found.
Wooting SDK failed to load.
Attempting to load LIFX SDK..
LIFX SDK Loaded
Game Language set to English.
No new updates currently available.
Attempting Attach..
DX11 Initiated
Attached to FFXIV
Game Running (Taylor Coln)

**Comment by logicallysynced** [comment]
Are you running Razer Synapse 2 or 3?

Are Chroma Apps enabled in Synapse?

Have you enabled your devices (i.e. keyboard) under the the devices tab of Chromatics by ticking the keyboard checkbox?

**Comment by MrCTT** [comment]
Changed to Razer Synapse 3 and Chromatics started working. 
I was using Razer Synapse 2 and everything you listed was enabled. I used it because it supported everything. 
Unfortunately v3.0 doesnt support my mouse, only the firefly and keyboard.
EDIT: Actually it seems that Chromatics still activates on my mouse even with Razer Synapse 3.0.

**Comment by logicallysynced** [comment]
Well I know it definitely will work on Synapse 2, as I develop and test the app with Synapse 2.

Chromatics doesn’t actually use Synapse to send lighting commands, it uses the Chroma SDK which is installed alongside Synapse. It’s possible it wasn’t installed correctly when you first installed Synapse 2.

I suggest removing both Synapse 2/3 and Razer SDK (you have to remove both) from your Programs & Features and reinstalling Synapse 2 (don’t install the SDK seperately) if you don’t want to use Synapse 3.

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
