### ISSUE TITLE
Main Menu is still active

### ISSUE THREAD

**Issue by Rimbatur** [roxaskeyheart/Chromatics#87]
I'm using a corsair k95 rgb platinum and an Logitech G600 mmo gaming mouse.
Chromatics does start, but produces an Error while attempting to attach to the game.
attaches nevertheless but seems to be stuck in the Main Menu is still active Phase.

LOG:
Starting Chromatics Version 2.4.1
Searching for devices.chromatics..
Attempting to load devices.chromatics..
devices.chromatics loaded.
Searching for settings.chromatics..
Attempting to load settings.chromatics..
settings.chromatics loaded.
Searching for mappings.chromatics..
Attempting to load mappings.chromatics..
mappings.chromatics loaded.
Attempting to load Razer SDK..
The Razer SDK (RzChromaSDK64.dll) Could not be found on this computer. Uninstall any previous versions of Razer SDK & Synapse and then reinstall Razer Synapse.
Razer SDK failed to load.
Attempting to load Logitech SDK..
Logitech SDK Loaded
Attempting to load Corsair SDK..
CUE SDK Loaded (2.18.127/2.24.50)
Attempting to initializer Coolermaster support...
Did not find any supported Coolermaster devices.
Coolermaster SDK failed to load.
Attempting to load SteelSeries GameSense SDK..
SteelSeries SDK failed to load. Please make sure SteelSeries Engine is running.
Attempting to load Wooting SDK..
No Wooting devices found.
Wooting SDK failed to load.
Attempting to load LIFX SDK..
LIFX SDK Loaded
Logitech Conflict Mode is already enabled.
Game Language set to German.
No new updates currently available.
Attempting Attach..
Error: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
Internal Error:    bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   bei System.Net.WebClient.DownloadString(Uri address)
   bei Sharlayan.Helpers.APIHelper.APIResponseToJSON(String uri)
   bei Sharlayan.Helpers.APIHelper.APIResponseToDictionary[T](ConcurrentDictionary`2 dictionary, String file, String uri)
   bei Sharlayan.Helpers.APIHelper.GetActions(ConcurrentDictionary`2 actions)
   bei Sharlayan.Helpers.ActionHelper.Resolve()
   bei Sharlayan.MemoryHandler.SetProcess(ProcessModel processModel, String gameLanguage, String patchVersion, Boolean useLocalCache, Boolean scanAllMemoryRegions)
   bei Chromatics.Chromatics.InitiateMemory() in D:\Git\Chromatics\Chromatics\Chromatics\FFXIVInterfaces\FFXIVInterface.cs:Zeile 255.
Waiting for Game Launch..
Attempting Attach..
DX11 Initiated
Attached to FFXIV
Main Menu is still active.

**Comment by logicallysynced** [comment]
Please try our latest beta version:

https://chromaticsffxiv.com/chromatics2/Chromatics2.4.2c-Portable.zip

**Comment by Rimbatur** [comment]
has fixed the problems. Thanks a lot.

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
