### ISSUE TITLE
Error with XML document, can't load mappings for chromatic

### ISSUE THREAD

**Issue by TSCTempo** [roxaskeyheart/Chromatics#91]
So I installed everything but I'm not entirely sure why this is happening. It recognizes that I have razer  synapse and SDK installed but I get this and I'm not entirely sure why or what to do. The lighting effects won't show when I play the game and I'm pretty sure this is why.

Starting Chromatics Version 2.4.5
Searching for devices.chromatics..
Attempting to load devices.chromatics..
devices.chromatics loaded.
Searching for settings.chromatics..
Attempting to load settings.chromatics..
settings.chromatics loaded.
Searching for mappings.chromatics..
Attempting to load mappings.chromatics..
**Error loading mappings.chromatics. Error: There is an error in XML document (2, 2).**
Attempting to load Razer SDK..
Razer SDK Loaded (1.0.0.0)
Attempting to load Logitech SDK..
Logitech SDK failed to load. Please make sure LGS is running.
Attempting to load Corsair SDK..
CUE SDK failed to load. Please make sure CUE2 is running.
Attempting to initializer Coolermaster support...
Did not find any supported Coolermaster devices.
Coolermaster SDK failed to load.
Attempting to load SteelSeries GameSense SDK..
SteelSeries SDK failed to load. Please make sure SteelSeries Engine is running.
Attempting to load Wooting SDK..
No Wooting devices found.
Wooting SDK failed to load.
Attempting to load LIFX SDK..
LIFX SDK Loaded
Game Language set to English.
No new updates currently available.
Waiting for Game Launch..
Attempting Attach..
DX11 Initiated
Attached to FFXIV
Main Menu is still active.
Game Running (Typeid: 1)

**Comment by logicallysynced** [comment]
If you close the app, open the Chromatics installation directory and delete mappings.chromatics and then restart Chromatics, does that fix the issue?

**Comment by TSCTempo** [comment]
It does not unfortunately, I deleted the mappings.chromatics but I still get the exact same message

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
