### ISSUE TITLE
chromatics crashes when ffxiv loads

### ISSUE THREAD

**Issue by rauvagol** [roxaskeyheart/Chromatics#92]
using the coolermaster mk750, it connects to chromatics fine, and attaches to ffxiv fine, but after selecting the character and loading in to the game, everything breaks and the program dies

relevant crash reports 

https://pastebin.com/9u19XaZs
https://pastebin.com/fdXwJjDX
https://pastebin.com/irsf0bsc

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
