### ISSUE TITLE
Chromatics not causing lighting effects on keyboard - Razer Chroma V2

### ISSUE THREAD

**Issue by ErikaNovus** [roxaskeyheart/Chromatics#93]
I've installed the app and booted up the game while Chromatics is running. 
The log shows that it has attached to the game but the lighting effects are still showing the default on the keyboard.

Startup log is as follows:
Starting Chromatics Version 2.4.6
Searching for devices.chromatics..
Attempting to load devices.chromatics..
devices.chromatics loaded.
Searching for settings.chromatics..
Attempting to load settings.chromatics..
settings.chromatics loaded.
Searching for mappings.chromatics..
Attempting to load mappings.chromatics..
mappings.chromatics loaded.
Attempting to load Razer SDK..
Razer SDK Loaded (1.0.0.0)
Attempting to load Logitech SDK..
Logitech SDK failed to load. Please make sure LGS is running.
Attempting to load Corsair SDK..
CUE SDK failed to load. Please make sure CUE2 is running.
Attempting to initializer Coolermaster support...
Did not find any supported Coolermaster devices.
Coolermaster SDK failed to load.
Attempting to load SteelSeries GameSense SDK..
Please disable the Discord profile in Engine Apps.
SteelSeries SDK Loaded.
Attempting to load Wooting SDK..
No Wooting devices found.
Wooting SDK failed to load.
Attempting to load LIFX SDK..
LIFX SDK Loaded
Game Language set to English.
No new updates currently available.
Waiting for Game Launch..
Attempting Attach..
DX11 Initiated
Attached to FFXIV
Main Menu is still active.
Game Running (Typeid: 1)

Seems to be running as it should be nothing I do makes it show any sort of special lighting effects on the keyboard.

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
