### ISSUE TITLE
Chromatics crashes on launch when LGS is open

### ISSUE THREAD

**Issue by Xotig** [roxaskeyheart/Chromatics#94]
I've gone through the steps for setting up Logitech Devices, but I'm still getting an error message whenever I launch chromatics while LGS is open.

![image](https://user-images.githubusercontent.com/3034651/51284219-6f138700-19b0-11e9-85a9-fe6e6fd96f2e.png)

This happens whether FFXIV is running or not. Launching without LGS active, Chromatics stays open, but I can't access the LCC controls. Tried manually setting the lccauto flag in the settings.chromatic file and still had the same results. I am running as an administrator.

Using a Logitech G910. LGS version 9.02.65, Chromatics version 2.4.6.

**Comment by CyberCasper** [comment]
Was having the same problem - solved by disabling ARX in the settings.chromatics file. This fix allowed the program to run when LGS was already running, but did NOT result in it working in game. Re-enabling ARX causes it to crash on the spot. Will continue playing with this tomorrow, as it seems like a cool bit of software.

NOTE: Chromatics no longer seems to hook into FFXIV completely with ARX disabled while LGS is running - it no longer displays my character name, instead saying only: 
"Attached to FFXIV
Main Menu is still active. 
Game Running (Typeid: 1)"
If you run it without LGS open at all you get
"Game Running ('Character Name')" which I assume is intended functionality.

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
