### ISSUE TITLE
connecting to DX9, have DX11

### ISSUE THREAD

**Issue by Karoiseka** [roxaskeyheart/Chromatics#95]
Hi.

I just downloaded this program to go with my brand new Razer Blackwidow Chroma v2 and FFXIV.  I have Win7, with DX11 installed (checked and verified), however, I keep getting this message on Chromatics when trying to use it with FFXIV.  

Attempting Attach..
DX9 Initiated
DX9 support has been phased out from Chromatics. Please use DX11 when using Chromatics.
Attached to FFXIV
Game stopped
Attempting Attach..
DX9 Initiated
DX9 support has been phased out from Chromatics. Please use DX11 when using Chromatics.
Attached to FFXIV
Game stopped

It's doing that on and on and on, every few seconds.  Obviously no colors are working either.

Help?

**Comment by logicallysynced** [comment]
Is FFXIV set to run DX11?

**Comment by Karoiseka** [comment]
I'll have to check, sorry bout the delay

**Comment by Karoiseka** [comment]
You know, I've had that game installed for years, and didn't realize that it wasn't set up with DX11.  Thanks, that fixed it!
