### ISSUE TITLE
Blank Chromatics tab in ACT

### ISSUE THREAD

**Issue by m0ngr3ll** [roxaskeyheart/Chromatics#97]
Setting up Chromatics in ACT, plugin enabled with no issues except opening the Chromatics tab gives me nothing but a blank tab

**Comment by logicallysynced** [comment]
The ACT plugin is suppose to be used in conjunction with the Chromatics app.

**Comment by m0ngr3ll** [comment]
Sorry could you explain what you mean?
Following the setup guide in Chromatics for ACT, with both programs running, results in a blank Chromatics tab within the ACT program.
![actchromaticsblank](https://user-images.githubusercontent.com/47580440/52678851-f52cda00-2f2a-11e9-878c-7aa4f0e9a2b1.png)

**Comment by logicallysynced** [comment]
The tab is suppose to be blank. Once both programs are working you can set stuff up in the Chromatics app, not in ACT.

**Comment by m0ngr3ll** [comment]
Ah! Stupid me. Thanks, I tried following guides that must have been outdated as their configurations were within the Chromatics tab of ACT itself. Thanks again!

**Comment by logicallysynced** [comment]
That was Version 1.0 of Chromatics.
