### ISSUE TITLE
Corsair SDK not load

### ISSUE THREAD

**Issue by gberon** [roxaskeyheart/Chromatics#98]
I have iCUE 3.13.94 with SDK enable and i have this error when i launch Chromatics :

Attempting to load Corsair SDK..
CUE SDK failed to load. EX: Can't find the CUE-SDK at one of the expected locations:
 'C:\Program Files (x86)\Chromatics\x64\CUESDK_2015.dll
C:\Program Files (x86)\Chromatics\x64\CUESDK.dll'
CUE SDK failed to load. Please make sure CUE2 is running.

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
